/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AreasDtoForecastRegions } from './areas-dto-forecast-regions';
import { CountyDto } from './county-dto';


export interface AreasDto {
    Counties?: Array<CountyDto>;
    CountryDescription?: string;
    CountryId: number;
    CountryName?: string;
    ForecastRegions?: AreasDtoForecastRegions;
    SortOrder: number;
}

