/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForecastRegionDto } from './forecast-region-dto';


export interface AreasDtoForecastRegions { 
    Avalanche?: Array<ForecastRegionDto>;
    Drought?: Array<ForecastRegionDto>;
    EarthFlow?: Array<ForecastRegionDto>;
    EventOnGlacier?: Array<ForecastRegionDto>;
    Flooding?: Array<ForecastRegionDto>;
    Ice?: Array<ForecastRegionDto>;
    IceFall?: Array<ForecastRegionDto>;
    Jokulhaup?: Array<ForecastRegionDto>;
    LandSlide?: Array<ForecastRegionDto>;
    NotSpecified?: Array<ForecastRegionDto>;
    RockFall?: Array<ForecastRegionDto>;
    Unknown?: Array<ForecastRegionDto>;
}

