/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AtAGlanceViewModel { 
    /**
     * Count of all attachments
     */
    AttachmentsCount?: number;
    CompetenceLevelTID?: number;
    DtObsTime: string;
    /**
     * Returns first attachement url from the observation or null
     */
    FirstAttachmentUrl?: string;
    FormNames?: Array<string>;
    GeoHazardTID?: number;
    Latitude: number;
    Longitude: number;
    NickName?: string;
    RegId: number;
    Title?: string;
    UtmEast: number;
    UtmNorth: number;
}

