/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AttachmentEditModel {
    Aspect?: number;
    AttachmentId?: number;
    AttachmentMimeType?: string;
    AttachmentUploadId?: string;
    Comment?: string;
    Copyright?: string;
    GeoHazardTID?: number;
    IsMainAttachment?: boolean;
    Photographer?: string;
    RegistrationTID?: number;
}

