/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Urls in different formats
 */
export interface AttachmentViewModelUrlFormats {
    Large?: string;
    Medium?: string;
    Original?: string;
    Raw?: string;
    Thumbnail?: string;
}

