/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentViewModelUrlFormats } from './attachment-view-model-url-formats';


export interface AttachmentViewModel {
    Aspect?: number;
    AttachmentId?: number;
    AttachmentMimeType?: string;
    Comment?: string;
    Copyright?: string;
    GeoHazardName?: string;
    GeoHazardTID?: number;
    IsMainAttachment?: boolean;
    IsSnowProfilePlot: boolean;
    Photographer?: string;
    RegistrationName?: string;
    RegistrationTID?: number;
    Url?: string;
    UrlFormats?: AttachmentViewModelUrlFormats;
}

