/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AvalancheActivityObs2EditModel { 
    AvalancheExtTID?: number;
    AvalCauseTID?: number;
    AvalPropagationTID?: number;
    AvalTriggerSimpleTID?: number;
    Comment?: string;
    DestructiveSizeTID?: number;
    DtEnd?: string;
    DtStart?: string;
    EstimatedNumTID?: number;
    ExposedHeight1?: number;
    ExposedHeight2?: number;
    ExposedHeightComboTID?: number;
    ValidExposition?: string;
}

