/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AvalancheEvaluation3EditModel {
    AvalancheDangerTID?: number;
    AvalancheDevelopment?: string;
    AvalancheEvaluation?: string;
    ForecastComment?: string;
    ForecastCorrectTID?: number;
}

