/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AvalancheActivityObsViewModel {
    Aspect: number;
    AvalancheActivityObsID: number;
    AvalancheName?: string;
    AvalancheTID?: number;
    AvalancheTriggerName?: string;
    AvalancheTriggerTID?: number;
    Comment?: string;
    DestructiveSizeName?: string;
    DestructiveSizeTID?: number;
    DtAvalancheTime: string;
    DtOffAvalancheTime: string;
    EstimatedNumName?: string;
    EstimatedNumTID?: number;
    HeigthStartZone: number;
    SnowLine?: number;
    SnowLineName?: string;
    TerrainStartZoneName?: string;
    TerrainStartZoneTID?: number;
}

