/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AvalancheActivityObs2ViewModel {
    AvalancheExtName?: string;
    AvalancheExtTID?: number;
    AvalCauseName?: string;
    AvalCauseTID?: number;
    AvalPropagationName?: string;
    AvalPropagationTID?: number;
    AvalTriggerSimpleName?: string;
    AvalTriggerSimpleTID?: number;
    Comment?: string;
    DestructiveSizeName?: string;
    DestructiveSizeTID?: number;
    DtEnd?: string;
    DtStart?: string;
    EstimatedNumName?: string;
    EstimatedNumTID?: number;
    ExposedHeight1?: number;
    ExposedHeight2?: number;
    ExposedHeightComboName?: string;
    ExposedHeightComboTID?: number;
    ValidExposition?: string;
}

