/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AvalancheObsEditModel {
    Aspect?: number;
    AvalancheTID?: number;
    AvalancheTriggerTID?: number;
    AvalCauseTID?: number;
    Comment?: string;
    DestructiveSizeTID?: number;
    DtAvalancheTime: string;
    DtEarliestAvalancheTime?: string;
    Extent?: Array<Array<number>>;
    FractureHeight?: number;
    FractureWidth?: number;
    HeightStartZone?: number;
    HeightStopZone?: number;
    RemotelyTriggered?: boolean;
    SnowLine?: number;
    StartExtent?: Array<Array<number>>;
    StartLat?: number;
    StartLong?: number;
    StopExtent?: Array<Array<number>>;
    StopLat?: number;
    StopLong?: number;
    TerrainStartZoneTID?: number;
    Trajectory?: string;
    ValidExposition?: string;
}

