/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';


export interface AvalancheEvaluation2ViewModel { 
    AvalancheDangerName?: string;
    AvalancheDangerTID?: number;
    AvalancheDevelopment?: string;
    AvalancheEvalProblems?: Array<AvalancheEvalProblemViewModel>;
    AvalancheEvaluation?: string;
    Comment?: string;
    ExposedClimateName?: string;
    ExposedClimateTID?: number;
    ExposedHeight1?: number;
    ExposedHeight2?: number;
    ExposedHeightComboName?: string;
    ExposedHeightComboTID?: number;
    ValidExposition?: string;
}

