/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CompressionTestViewModel {
    Comment?: string;
    CompressionTestName?: string;
    CompressionTestTID?: number;
    ComprTestFractureName?: string;
    ComprTestFractureTID?: number;
    FractureDepth?: number;
    IncludeInSnowProfile?: boolean;
    PropagationName?: string;
    PropagationTID?: number;
    PstX?: number;
    PstY?: number;
    RbRelease?: number;
    StabilityEvalName?: string;
    StabilityEvalTID?: number;
    TapsFracture?: number;
    TapsFullPropagation?: number;
}

