/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CompressionTestEditModel {
    Comment?: string;
    CompressionTestTID?: number;
    ComprTestFractureTID?: number;
    FractureDepth?: number;
    IncludeInSnowProfile?: boolean;
    PropagationTID?: number;
    PstX?: number;
    PstY?: number;
    RbRelease?: number;
    StabilityEvalTID?: number;
    TapsFracture?: number;
    TapsFullPropagation?: number;
}

