/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateTripDto { 
    Comment?: string;
    DeviceGuid: string;
    GeoHazardID: number;
    Lat?: string;
    Lng?: string;
    ObservationExpectedMinutes: number;
    TripTypeID: number;
}

