/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentViewModel } from './attachment-view-model';
import { LatLng } from './lat-lng';


export interface DamageObsViewModel {
    Attachments?: Array<AttachmentViewModel>;
    Comment?: string;
    DamagePosition?: LatLng;
    DamageTypeName?: string;
    DamageTypeTID: number;
    GeoHazardName?: string;
    GeoHazardTID?: number;
}

