/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LatLng } from './lat-lng';
import { AttachmentEditModel } from './attachment-edit-model';


export interface DamageObsEditModel {
    Attachments?: Array<AttachmentEditModel>;
    Comment?: string;
    DamagePosition?: LatLng;
    DamageTypeTID: number;
    GeoHazardTID?: number;
}

