/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DangerObsViewModel {
    Comment?: string;
    DangerSignName?: string;
    DangerSignTID?: number;
    GeoHazardName?: string;
    GeoHazardTID?: number;
}

