/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForecastRegionSubRegionDto } from './forecast-region-sub-region-dto';


export interface ForecastRegionDto {
    Id: number;
    IsRegionForGrouping: boolean;
    SortOrder: number;
    SubRegions?: Array<ForecastRegionSubRegionDto>;
    Text?: string;
}

