/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ForecastRegionSubRegionDto { 
    Id: number;
    RegionType?: string;
    SortOrder: number;
    Text?: string;
}

