/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlViewModel } from './url-view-model';


export interface GeneralObservationViewModel {
    Comment?: string;
    GeoHazardName?: string;
    GeoHazardTID?: number;
    ObsComment?: string;
    ObsHeader?: string;
    Urls?: Array<UrlViewModel>;
}

