/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlEditModel } from './url-edit-model';


export interface GeneralObservationEditModel {
    Comment?: string;
    GeoHazardTID?: number;
    ObsComment?: string;
    ObsHeader?: string;
    Urls?: Array<UrlEditModel>;
}

