/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GeoLocationInfo {
    AdminAreaId?: string;
    AdminAreaName?: string;
    Country?: string;
    CountryCode?: string;
    Masl?: number;
    Municipality?: string;
    MunicipalityId?: string;
    Name?: string;
    Steepness?: number;
    WarningRegionId?: string;
    WarningRegionName?: string;
}

