/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IceThicknessLayerEditModel } from './ice-thickness-layer-edit-model';


export interface IceThicknessEditModel {
    Comment?: string;
    IceHeightAfter?: number;
    IceHeightBefore?: number;
    IceThicknessLayers?: Array<IceThicknessLayerEditModel>;
    IceThicknessSum?: number;
    SlushSnow?: number;
    SnowDepth?: number;
}

