/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IceThicknessLayerViewModel } from './ice-thickness-layer-view-model';


export interface IceThicknessViewModel {
    Comment?: string;
    IceHeightAfter?: number;
    IceHeightBefore?: number;
    IceThicknessLayers?: Array<IceThicknessLayerViewModel>;
    IceThicknessSum?: number;
    SlushSnow?: number;
    SnowDepth?: number;
}

