/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlViewModel } from './url-view-model';


export interface IceCoverViewModel {
    Comment?: string;
    IceCapacityName?: string;
    IceCapacityTID?: number;
    IceCoverAfterName?: string;
    IceCoverAfterTID?: number;
    IceCoverBeforeName?: string;
    IceCoverBeforeTID?: number;
    IceCoverName?: string;
    IceCoverTID?: number;
    IceSkateabilityName?: string;
    IceSkateabilityTID?: number;
    Urls?: Array<UrlViewModel>;
}

