/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlEditModel } from './url-edit-model';


export interface IceCoverEditModel {
    Comment?: string;
    IceCapacityTID?: number;
    IceCoverAfterTID?: number;
    IceCoverBeforeTID?: number;
    IceCoverTID?: number;
    IceSkateabilityTID?: number;
    Urls?: Array<UrlEditModel>;
}

