/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface IceThicknessLayerEditModel { 
    /**
     * Comment
     */
    Comment?: string;
    /**
     * IceLayerThickness
     */
    IceLayerThickness?: number;
    /**
     * The IceLayerKD unique identifier
     */
    IceLayerTID?: number;
}

