/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlEditModel } from './url-edit-model';


export interface IncidentEditModel {
    ActivityInfluencedTID?: number;
    CasualtiesNum?: number;
    Comment?: string;
    DamageExtentTID?: number;
    DeadNum?: number;
    DtEndTime?: string;
    EvacuatedNum?: number;
    ForecastAccurateTID?: number;
    GeoHazardTID?: number;
    HarmedNum?: number;
    IncidentHeader?: string;
    IncidentIngress?: string;
    IncidentText?: string;
    IncidentURLs?: Array<UrlEditModel>;
    InvolvedNum?: number;
    LocalKnowledgeTID?: number;
    LocalTouristTID?: number;
    MaterialDamages?: boolean;
    RescueTID?: number;
    SafetyGearTID?: number;
    SlopeActivityTID?: number;
    TrafficObstructed?: boolean;
}

