/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlViewModel } from './url-view-model';


export interface IncidentViewModel {
    ActivityInfluencedName?: string;
    ActivityInfluencedTID?: number;
    CasualtiesNum?: number;
    Comment?: string;
    DamageExtentName?: string;
    DamageExtentTID?: number;
    DeadNum?: number;
    DtEndTime?: string;
    EvacuatedNum?: number;
    ForecastAccurateName?: string;
    ForecastAccurateTID?: number;
    GeoHazardName?: string;
    GeoHazardTID?: number;
    HarmedNum?: number;
    IncidentHeader?: string;
    IncidentIngress?: string;
    IncidentText?: string;
    IncidentURLs?: Array<UrlViewModel>;
    InvolvedNum?: number;
    LocalKnowledgeName?: string;
    LocalKnowledgeTID?: number;
    LocalTouristName?: string;
    LocalTouristTID?: number;
    MaterialDamages?: boolean;
    RescueName?: string;
    RescueTID?: number;
    SafetyGearName?: string;
    SafetyGearTID?: number;
    SlopeActivityName?: string;
    SlopeActivityTID?: number;
    TrafficObstructed?: boolean;
}

