/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KdvElement } from './kdv-element';


export interface KdvElementsResponseDto {
    KdvRepositories?: { [key: string]: Array<KdvElement>; };
    ViewRepositories?: any;
}

