/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlEditModel } from './url-edit-model';


export interface LandslideEditModel {
    ActivityInfluencedTID?: number;
    Comment?: string;
    DamageExtentTID?: number;
    DtLandSlideTime: string;
    DtLandSlideTimeEnd?: string;
    Extent?: Array<Array<number>>;
    ForecastAccurateTID?: number;
    GeoHazardTID?: number;
    LandSlideSizeTID?: number;
    LandSlideTID?: number;
    LandSlideTriggerTID?: number;
    StartExtent?: Array<Array<number>>;
    StartLat?: number;
    StartLong?: number;
    StopExtent?: Array<Array<number>>;
    StopLat?: number;
    StopLong?: number;
    Urls?: Array<UrlEditModel>;
}

