/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UrlViewModel } from './url-view-model';


export interface LandslideViewModel {
    ActivityInfluencedName?: string;
    ActivityInfluencedTID?: number;
    Comment?: string;
    DamageExtentName?: string;
    DamageExtentTID?: number;
    DtLandSlideTime: string;
    DtLandSlideTimeEnd?: string;
    Extent?: Array<Array<number>>;
    ForecastAccurateName?: string;
    ForecastAccurateTID?: number;
    GeoHazardName?: string;
    GeoHazardTID?: number;
    LandSlideName?: string;
    LandSlideSizeName?: string;
    LandSlideSizeTID?: number;
    LandSlideTID?: number;
    LandSlideTriggerName?: string;
    LandSlideTriggerTID?: number;
    StartExtent?: Array<Array<number>>;
    StartLat?: number;
    StartLong?: number;
    StopExtent?: Array<Array<number>>;
    StopLat?: number;
    StopLong?: number;
    Urls?: Array<UrlViewModel>;
}

