/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ObserverGroupDto } from './observer-group-dto';
import { ObserverCompetenceDto } from './observer-competence-dto';


export interface MyPageData { 
    Adrnr?: number;
    Competence?: Array<ObserverCompetenceDto>;
    DefaultMunicipality?: string;
    DtRegTime?: string;
    Email?: string;
    FirstName?: string;
    Guid: string;
    LastName?: string;
    LastRegistrationDate?: string;
    MainGeohazardTID: number;
    MemberOfGroups?: Array<ObserverGroupDto>;
    MobPhoneNr?: string;
    NickName?: string;
    NumberOfObservations: number;
    /**
     * Returns unique id that identifies an observer
     */
    ObserverId: number;
    PendingInvitationsToGroups?: Array<ObserverGroupDto>;
    Roles?: Array<string>;
    WorkPlace?: string;
}

