/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ObsLocationViewModel {
    CountryId?: number;
    CountryName?: string;
    ForecastRegionName?: string;
    ForecastRegionTID?: number;
    Height?: number;
    Latitude: number;
    LocationDescription?: string;
    LocationName?: string;
    Longitude: number;
    MunicipalName?: string;
    MunicipalNo?: string;
    ObsLocationID?: number;
    Title?: string;
    Uncertainty?: number;
    UTMSourceName?: string;
    UTMSourceTID?: number;
}

