/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LatLngObject } from './lat-lng-object';


export interface ObsLocationsResponseDtoV2 {
    Distance: number;
    GeoHazardId?: number;
    Id: number;
    LatLngObject?: LatLngObject;
    LocationDescription?: string;
    Name?: string;
    ObserverGroupId?: number;
    ObserverGroupName?: string;
    ObserverNickName?: string;
}

