/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ObsLocationEditModel {
    Latitude: number;
    LocationDescription?: string;
    LocationName?: string;
    Longitude: number;
    ObsLocationID?: number;
    Uncertainty?: number;
    UTMSourceTID?: number;
}

