/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ObserverViewModel { 
    CompetenceLevelName?: string;
    CompetenceLevelTID: number;
    NickName?: string;
    ObserverID: number;
}

