/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ObserverGroupDto } from './observer-group-dto';


export interface ObserverResponseDto {
    Guid: string;
    Nick?: string;
    ObserverGroup?: Array<ObserverGroupDto>;
}

