/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export const Operator = {
    NUMBER_0: 0
} as const;
export type Operator = typeof Operator[keyof typeof Operator];

