/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProblemDetails { 
  [key: string]: any | any;


    detail?: string;
    instance?: string;
    status?: number;
    title?: string;
    type?: string;
}

