/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Operator } from './operator';


/**
 * Filter by property value
 */
export interface PropertyFilter {
    Name?: string;
    Operator: Operator;
    Value?: string;
}
export namespace PropertyFilter {
}


