/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValueKind } from './value-kind';


export interface RegObsGenericValue { 
    Header?: string;
    Kind: ValueKind;
    /** Readonly property */
    KindType?: string;
    Value?: any;
}

export namespace RegObsGenericValue {
}

