/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentViewModel } from './attachment-view-model';


export interface RegistrationsWithAttachments {
    Attachments?: Array<AttachmentViewModel>;
    RegId: number;
}

