/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RegistrationTypeSubTypeDto } from './registration-type-sub-type-dto';


export interface RegistrationTypeDto {
    Id: number;
    Name?: string;
    SortOrder: number;
    SubTypes?: Array<RegistrationTypeSubTypeDto>;
}

