/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IceThicknessViewModel } from './ice-thickness-view-model';
import { SnowSurfaceViewModel } from './snow-surface-view-model';
import { IncidentViewModel } from './incident-view-model';
import { ObserverViewModel } from './observer-view-model';
import { GeoHazardTypes } from './geo-hazard-types';
import { WeatherViewModel } from './weather-view-model';
import { DamageObsViewModel } from './damage-obs-view-model';
import { LandslideViewModel } from './landslide-view-model';
import { WaterLevelViewModel } from './water-level-view-model';
import { SnowProfileViewModel } from './snow-profile-view-model';
import { AvalancheObsViewModel } from './avalanche-obs-view-model';
import { AvalancheActivityObsViewModel } from './avalanche-activity-obs-view-model';
import { AvalancheDangerObsViewModel } from './avalanche-danger-obs-view-model';
import { SnowCoverObsViewModel } from './snow-cover-obs-view-model';
import { AvalancheEvaluation3ViewModel } from './avalanche-evaluation3-view-model';
import { CompressionTestViewModel } from './compression-test-view-model';
import { IceCoverViewModel } from './ice-cover-view-model';
import { AvalancheEvaluationViewModel } from './avalanche-evaluation-view-model';
import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';
import { ObsLocationViewModel } from './obs-location-view-model';
import { AvalancheActivityObs2ViewModel } from './avalanche-activity-obs2-view-model';
import { AttachmentViewModel } from './attachment-view-model';
import { Waterlevel2ViewModel } from './waterlevel2-view-model';
import { DangerObsViewModel } from './danger-obs-view-model';
import { AvalancheEvaluation2ViewModel } from './avalanche-evaluation2-view-model';
import { AvalancheEvalProblem2ViewModel } from './avalanche-eval-problem2-view-model';
import { Summary } from './summary';
import { GeneralObservationViewModel } from './general-observation-view-model';


export interface RegistrationViewModel { 
    Anonymous?: boolean;
    Attachments?: Array<AttachmentViewModel>;
    AttachmentSummaries?: Array<Summary>;
    AvalancheActivityObs?: Array<AvalancheActivityObsViewModel>;
    AvalancheActivityObs2?: Array<AvalancheActivityObs2ViewModel>;
    AvalancheDangerObs?: Array<AvalancheDangerObsViewModel>;
    AvalancheEvalProblem?: Array<AvalancheEvalProblemViewModel>;
    AvalancheEvalProblem2?: Array<AvalancheEvalProblem2ViewModel>;
    AvalancheEvaluation?: AvalancheEvaluationViewModel;
    AvalancheEvaluation2?: AvalancheEvaluation2ViewModel;
    AvalancheEvaluation3?: AvalancheEvaluation3ViewModel;
    AvalancheObs?: AvalancheObsViewModel;
    CompressionTest?: Array<CompressionTestViewModel>;
    DamageObs?: Array<DamageObsViewModel>;
    DangerObs?: Array<DangerObsViewModel>;
    DtChangeTime?: string;
    DtObsTime: string;
    DtRegTime: string;
    ExternalReferenceId?: string;
    GeneralObservation?: GeneralObservationViewModel;
    GeoHazardName?: string;
    /**
     * NotSpecified = 0, Avalanche = 10, EarthFlow = 20, LandSlide = 30, RockFall = 40, IceFall = 50, Flooding = 60, Ice = 70, EventOnGlacier = 100, Jøkulhaup = 110, Drought = 200, Unknown = 999
     */
    GeoHazardTID: GeoHazardTypes;
    IceCoverObs?: IceCoverViewModel;
    IceThickness?: IceThicknessViewModel;
    Incident?: IncidentViewModel;
    LandSlideObs?: LandslideViewModel;
    Observer: ObserverViewModel;
    ObserverGroupID?: number;
    ObserverGroupName?: string;
    ObsLocation: ObsLocationViewModel;
    RegId: number;
    SnowCoverObs?: SnowCoverObsViewModel;
    SnowProfile?: AttachmentViewModel;
    SnowProfile2?: SnowProfileViewModel;
    SnowSurfaceObservation?: SnowSurfaceViewModel;
    SourceName?: string;
    SourceTID: number;
    Summaries?: Array<Summary>;
    WaterLevel?: WaterLevelViewModel;
    WaterLevel2?: Waterlevel2ViewModel;
    WeatherObservation?: WeatherViewModel;
}

export namespace RegistrationViewModel {
}

