/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeoHazardTypes } from './geo-hazard-types';
import { LangKey } from './lang-key';


export interface SearchSideBarRequestDto {
    GeoHazards?: Array<GeoHazardTypes>;
    LangKey: LangKey;
}
export namespace SearchSideBarRequestDto {
}


