/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RegistrationTypeCriteriaDto } from './registration-type-criteria-dto';
import { WithinRadiusCriteriaDto } from './within-radius-criteria-dto';
import { PropertyFilter } from './property-filter';
import { WithinExtentCriteriaDto } from './within-extent-criteria-dto';


/**
 * Use this to filter out registrations.
 */
export interface SearchCriteriaRequestDto {
    AscendingOrder: boolean;
    Counties?: Array<string>;
    Countries?: Array<number>;
    Extent?: WithinExtentCriteriaDto;
    FromDtChangeTime?: string;
    FromDtObsTime?: string;
    GroupId?: number;
    LangKey?: number;
    LocationId?: number;
    NumberOfRecords?: number;
    ObserverCompetence?: Array<number>;
    ObserverGuid?: string;
    ObserverId?: number;
    ObserverNickName?: string;
    Offset?: number;
    OrderBy?: string;
    PropertyFilters?: Array<PropertyFilter>;
    Radius?: WithinRadiusCriteriaDto;
    RegId?: number;
    SelectedGeoHazards?: Array<number>;
    SelectedRegions?: Array<number>;
    SelectedRegistrationTypes?: Array<RegistrationTypeCriteriaDto>;
    TextSearch?: string;
    TimeZone?: string;
    ToDtChangeTime?: string;
    ToDtObsTime?: string;
}

