/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RegistrationTypeDto } from './registration-type-dto';


export interface SearchSideBarDtoRegistrationTypes { 
    Avalanche?: Array<RegistrationTypeDto>;
    Drought?: Array<RegistrationTypeDto>;
    EarthFlow?: Array<RegistrationTypeDto>;
    EventOnGlacier?: Array<RegistrationTypeDto>;
    Flooding?: Array<RegistrationTypeDto>;
    Ice?: Array<RegistrationTypeDto>;
    IceFall?: Array<RegistrationTypeDto>;
    Jokulhaup?: Array<RegistrationTypeDto>;
    LandSlide?: Array<RegistrationTypeDto>;
    NotSpecified?: Array<RegistrationTypeDto>;
    RockFall?: Array<RegistrationTypeDto>;
    Unknown?: Array<RegistrationTypeDto>;
}

