/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ObserverCompetenceLevelDto } from './observer-competence-level-dto';


export interface SearchSideBarDtoObserverCompetenceLevels { 
    Avalanche?: Array<ObserverCompetenceLevelDto>;
    Drought?: Array<ObserverCompetenceLevelDto>;
    EarthFlow?: Array<ObserverCompetenceLevelDto>;
    EventOnGlacier?: Array<ObserverCompetenceLevelDto>;
    Flooding?: Array<ObserverCompetenceLevelDto>;
    Ice?: Array<ObserverCompetenceLevelDto>;
    IceFall?: Array<ObserverCompetenceLevelDto>;
    Jokulhaup?: Array<ObserverCompetenceLevelDto>;
    LandSlide?: Array<ObserverCompetenceLevelDto>;
    NotSpecified?: Array<ObserverCompetenceLevelDto>;
    RockFall?: Array<ObserverCompetenceLevelDto>;
    Unknown?: Array<ObserverCompetenceLevelDto>;
}

