/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnowDensityModel } from './snow-density-model';
import { StratProfileViewModel } from './strat-profile-view-model';
import { AttachmentViewModel } from './attachment-view-model';
import { SnowTempModel } from './snow-temp-model';


export interface SnowProfileViewModel {
    Comment?: string;
    Exposition?: number;
    IsProfileToGround?: boolean;
    PlotImage?: AttachmentViewModel;
    SlopeAngle?: number;
    SnowDensity?: Array<SnowDensityModel>;
    SnowTemp?: SnowTempModel;
    StratProfile?: StratProfileViewModel;
    TotalDepth: number;
}

