/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnowSurfaceEditModel {
    Comment?: string;
    HeightLimitLayeredSnow?: number;
    NewSnowDepth24?: number;
    NewSnowLine?: number;
    SkiConditionsTID?: number;
    SnowDepth?: number;
    SnowDriftTID?: number;
    SnowLine?: number;
    SnowSurfaceTID?: number;
    SurfaceWaterContentTID?: number;
}

