/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnowCoverObsViewModel {
    Comment?: string;
    CriticalLayerExists?: boolean;
    CriticalLayerLocation?: number;
    CriticalLayerName?: string;
    CriticalLayerTID?: number;
    DepthHoarThickness?: number;
    SnowPilotRef?: string;
}

