/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnowDensityLayerModel } from './snow-density-layer-model';


export interface SnowDensityModel { 
    Comment?: string;
    CylinderDiameter?: number;
    Layers?: Array<SnowDensityLayerModel>;
    TareWeight?: number;
}

