/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnowDensityModel } from './snow-density-model';
import { StratProfileEditModel } from './strat-profile-edit-model';
import { SnowTempModel } from './snow-temp-model';


export interface SnowProfileEditModel {
    Comment?: string;
    Exposition?: number;
    IsProfileToGround?: boolean;
    SlopeAngle?: number;
    SnowDensity?: Array<SnowDensityModel>;
    SnowTemp?: SnowTempModel;
    StratProfile?: StratProfileEditModel;
}

