/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnowDensityLayerModel {
    Comment?: string;
    Density?: number;
    Depth?: number;
    SortOrder: number;
    Thickness?: number;
    WaterEquivalent: number;
    Weight: number;
}

