/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnowCoverObsViewModel { 
    /**
     * Comment.
     */
    Comment?: string;
    /**
     * CriticalLayerExists
     */
    CriticalLayerExists?: boolean;
    /**
     * CriticalLayerLocation
     */
    CriticalLayerLocation?: number;
    CriticalLayerName?: string;
    /**
     * The CriticalLayerKD unique identifier
     */
    CriticalLayerTID?: number;
    /**
     * DepthHoarThickness
     */
    DepthHoarThickness?: number;
    /**
     * SnowPilotRef
     */
    SnowPilotRef?: string;
}

