/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnowTempObsModel } from './snow-temp-obs-model';


export interface SnowTempModel { 
    Layers?: Array<SnowTempObsModel>;
}

