/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnowSurfaceViewModel {
    Comment?: string;
    FootPenetration?: number;
    HeightLimitLayeredSnow?: number;
    NewSnowDepth24?: number;
    NewSnowLine?: number;
    SkiConditionsName?: string;
    SkiConditionsTID?: number;
    SnowDepth?: number;
    SnowDriftName?: string;
    SnowDriftTID?: number;
    SnowLine?: number;
    SnowSurfaceName?: string;
    SnowSurfaceTID?: number;
    SnowWindDepth24?: number;
    SurfaceRougnessName?: string;
    SurfaceRougnessTID?: number;
    SurfaceWaterContentName?: string;
    SurfaceWaterContentTID?: number;
}

