/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StratProfileLayerViewModel {
    Comment?: string;
    CriticalLayerTID?: number;
    CriticalLayerTName?: string;
    DepthTop?: number;
    GrainFormPrimaryTID?: number;
    GrainFormPrimaryTName?: string;
    GrainFormSecondaryTID?: number;
    GrainFormSecondaryTName?: string;
    GrainSizeAvg?: number;
    GrainSizeAvgMax?: number;
    HardnessBottomTID?: number;
    HardnessBottomTName?: string;
    HardnessTID?: number;
    HardnessTName?: string;
    SortOrder: number;
    Thickness?: number;
    WetnessTID?: number;
    WetnessTName?: string;
}

