/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StratProfileLayerEditModel {
    Comment?: string;
    CriticalLayerTID?: number;
    DepthTop?: number;
    GrainFormPrimaryTID?: number;
    GrainFormSecondaryTID?: number;
    GrainSizeAvg?: number;
    GrainSizeAvgMax?: number;
    HardnessBottomTID?: number;
    HardnessTID?: number;
    SortOrder: number;
    Thickness?: number;
    WetnessTID?: number;
}

