/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StratProfileLayerViewModel } from './strat-profile-layer-view-model';


export interface StratProfileViewModel {
    Layers?: Array<StratProfileLayerViewModel>;
    TotalDepth: number;
}

