/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RegObsGenericValue } from './reg-obs-generic-value';


export interface Summary { 
    RegistrationName?: string;
    RegistrationTID: number;
    Summaries?: Array<RegObsGenericValue>;
}

