/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentEditModel } from './attachment-edit-model';


export interface WaterLevelMeasurementEditModel {
    Attachments?: Array<AttachmentEditModel>;
    Comment?: string;
    DtMeasurementTime: string;
    WaterLevelMeasurementId?: number;
    WaterLevelValue?: number;
}

