/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WaterLevelViewModel {
    Comment?: string;
    IsRiver: boolean;
    MeasuredDischarge?: number;
    WaterLevelDescribed?: string;
    WaterLevelRefName?: string;
    WaterLevelRefTID: number;
    WaterLevelValue?: number;
}

