/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentViewModel } from './attachment-view-model';


export interface WaterLevelMeasurementViewModel {
    Attachments?: Array<AttachmentViewModel>;
    Comment?: string;
    DtMeasurementTime: string;
    WaterLevelMeasurementId: number;
    WaterLevelValue?: number;
}

