/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WaterLevelMeasurementEditModel } from './water-level-measurement-edit-model';


export interface Waterlevel2EditModel { 
    Comment?: string;
    /**
     * Flood polygon area, List(lon, lat)
     */
    Extent?: Array<Array<number>>;
    MarkingReferenceTID?: number;
    MarkingTypeTID?: number;
    MeasurementReferenceTID?: number;
    MeasurementTypeTID?: number;
    MeasuringToolDescription?: string;
    ObservationTimingTID?: number;
    WaterAstrayTID?: number;
    WaterLevelMeasurement?: Array<WaterLevelMeasurementEditModel>;
    WaterLevelMethodTID?: number;
    WaterLevelStateTID?: number;
}

