/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WeatherViewModel {
    AirTemperature?: number;
    CloudCover?: number;
    Comment?: string;
    PrecipitationName?: string;
    PrecipitationTID?: number;
    WindDirection?: number;
    WindDirectionName?: string;
    WindSpeed?: number;
}

