/* tslint:disable */
import { DangerObsDto } from './danger-obs-dto';
import { AvalancheActivityObsDto } from './avalanche-activity-obs-dto';
import { AvalancheActivityObs2Dto } from './avalanche-activity-obs-2dto';
import { AvalancheDangerObsDto } from './avalanche-danger-obs-dto';
import { AvalancheEvalProblem2Dto } from './avalanche-eval-problem-2dto';
import { AvalancheEvaluation3Dto } from './avalanche-evaluation-3dto';
import { AvalancheObsDto } from './avalanche-obs-dto';
import { CompressionTestDto } from './compression-test-dto';
import { GeneralObservationEditModel } from './general-observation-edit-model';
import { IceCoverObsDto } from './ice-cover-obs-dto';
import { IceThicknessDto } from './ice-thickness-dto';
import { IncidentDto } from './incident-dto';
import { LandSlideObsDto } from './land-slide-obs-dto';
import { ObsLocationDto } from './obs-location-dto';
import { PictureRequestDto } from './picture-request-dto';
import { SnowCoverObsDto } from './snow-cover-obs-dto';
import { SnowProfileDto } from './snow-profile-dto';
import { SnowSurfaceObservationDto } from './snow-surface-observation-dto';
import { WaterLevelDto } from './water-level-dto';
import { WeatherObservationDto } from './weather-observation-dto';
import { WaterLevel2Dto } from './water-level-2dto';
import { DamageObsDto } from './damage-obs-dto';
import { DensityProfileDto } from './density-profile-dto';
export interface CreateRegistrationRequestDto {
  DangerObs?: Array<DangerObsDto>;
  Id: string;
  DtObsTime: string;
  ObserverGuid: string;
  Email?: boolean;
  ObsLocationID?: number;
  ObserverGroupID?: number;
  Comment?: string;
  SourceTID?: number;
  AvalancheActivityObs?: Array<AvalancheActivityObsDto>;
  AvalancheActivityObs2?: Array<AvalancheActivityObs2Dto>;
  AvalancheDangerObs?: Array<AvalancheDangerObsDto>;
  AvalancheEvalProblem2?: Array<AvalancheEvalProblem2Dto>;
  AvalancheEvaluation3?: AvalancheEvaluation3Dto;
  AvalancheObs?: AvalancheObsDto;
  CompressionTest?: Array<CompressionTestDto>;
  GeoHazardTID: 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 100 | 110 | 200 | 999;
  GeneralObservation?: GeneralObservationEditModel;
  IceCoverObs?: IceCoverObsDto;
  IceThickness?: IceThicknessDto;
  Incident?: IncidentDto;
  LandSlideObs?: LandSlideObsDto;
  ObsLocation?: ObsLocationDto;
  Picture?: Array<PictureRequestDto>;
  SnowCoverObs?: SnowCoverObsDto;
  SnowProfile?: PictureRequestDto;
  SnowProfile2?: SnowProfileDto;
  SnowSurfaceObservation?: SnowSurfaceObservationDto;
  WaterLevel?: WaterLevelDto;
  WeatherObservation?: WeatherObservationDto;
  WaterLevel2?: WaterLevel2Dto;
  DamageObs?: Array<DamageObsDto>;
  DensityProfile?: DensityProfileDto;
}
