/* tslint:disable */
import { ObserverViewModel } from './observer-view-model';
import { ObsLocationViewModel } from './obs-location-view-model';
import { AttachmentViewModel } from './attachment-view-model';
import { AvalancheActivityObsViewModel } from './avalanche-activity-obs-view-model';
import { AvalancheActivityObs2ViewModel } from './avalanche-activity-obs-2view-model';
import { AvalancheDangerObsViewModel } from './avalanche-danger-obs-view-model';
import { AvalancheEvalProblem2ViewModel } from './avalanche-eval-problem-2view-model';
import { AvalancheEvaluation3ViewModel } from './avalanche-evaluation-3view-model';
import { AvalancheEvaluationViewModel } from './avalanche-evaluation-view-model';
import { AvalancheObsViewModel } from './avalanche-obs-view-model';
import { CompressionTestViewModel } from './compression-test-view-model';
import { DangerObsViewModel } from './danger-obs-view-model';
import { GeneralObservationViewModel } from './general-observation-view-model';
import { IceCoverViewModel } from './ice-cover-view-model';
import { IceThicknessViewModel } from './ice-thickness-view-model';
import { IncidentViewModel } from './incident-view-model';
import { LandslideViewModel } from './landslide-view-model';
import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';
import { SnowCoverObsViewModel } from './snow-cover-obs-view-model';
import { SnowProfileViewModel } from './snow-profile-view-model';
import { SnowSurfaceViewModel } from './snow-surface-view-model';
import { WaterLevelViewModel } from './water-level-view-model';
import { WeatherViewModel } from './weather-view-model';
import { Waterlevel2ViewModel } from './waterlevel-2view-model';
import { DamageObsViewModel } from './damage-obs-view-model';
import { AvalancheEvaluation2ViewModel } from './avalanche-evaluation-2view-model';
import { Summary } from './summary';
export interface RegistrationViewModel {
  RegID?: number;
  GeoHazardTID?: 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 100 | 110 | 200 | 999;
  GeoHazardName?: string;
  LangKey?: number;
  DtObsTime?: string;
  DtRegTime?: string;
  DtChangeTime?: string;
  SourceTID?: number;
  SourceName?: string;
  Observer?: ObserverViewModel;
  ObsLocation?: ObsLocationViewModel;
  Attachments?: Array<AttachmentViewModel>;
  AvalancheActivityObs?: Array<AvalancheActivityObsViewModel>;
  AvalancheActivityObs2?: Array<AvalancheActivityObs2ViewModel>;
  AvalancheDangerObs?: Array<AvalancheDangerObsViewModel>;
  AvalancheEvalProblem2?: Array<AvalancheEvalProblem2ViewModel>;
  AvalancheEvaluation3?: AvalancheEvaluation3ViewModel;
  AvalancheEvaluation?: AvalancheEvaluationViewModel;
  AvalancheObs?: AvalancheObsViewModel;
  CompressionTest?: Array<CompressionTestViewModel>;
  DangerObs?: Array<DangerObsViewModel>;
  GeneralObservation?: GeneralObservationViewModel;
  IceCoverObs?: IceCoverViewModel;
  IceThickness?: IceThicknessViewModel;
  Incident?: IncidentViewModel;
  SnowProfile?: AttachmentViewModel;
  LandSlideObs?: LandslideViewModel;
  AvalancheEvalProblem?: Array<AvalancheEvalProblemViewModel>;
  SnowCoverObs?: SnowCoverObsViewModel;
  SnowProfile2?: SnowProfileViewModel;
  SnowSurfaceObservation?: SnowSurfaceViewModel;
  WaterLevel?: WaterLevelViewModel;
  WeatherObservation?: WeatherViewModel;
  WaterLevel2?: Waterlevel2ViewModel;
  DamageObs?: Array<DamageObsViewModel>;
  AvalancheEvaluation2?: AvalancheEvaluation2ViewModel;
  Summaries?: Array<Summary>;
  AttachmentSummaries?: Array<Summary>;
}
