# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 14.x'
  inputs:
    versionSpec: 14.x
    checkLatest: true

- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: '8a4eb7ac-653f-40c8-a421-d0a145352828'
    retryCount: 5

- task: CopyFiles@2
  displayName: 'Copy Files to: ./src/assets'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: apikey.json
    TargetFolder: ./src/assets

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'Install Ionic CLI'
  script: npm install -g @ionic/cli

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build --source-map'
  continueOnError: true

- task: Npm@1
  displayName: 'npm run tests'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TESTS-*.xml'
  inputs:
    testResultsFiles: '**/TESTS-*.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from **/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
    failIfCoverageEmpty: true
