/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForecastRegionDto } from './forecast-region-dto';


export interface AreasDtoForecastRegions { 
    NotSpecified?: Array<ForecastRegionDto>;
    Avalanche?: Array<ForecastRegionDto>;
    EarthFlow?: Array<ForecastRegionDto>;
    LandSlide?: Array<ForecastRegionDto>;
    RockFall?: Array<ForecastRegionDto>;
    IceFall?: Array<ForecastRegionDto>;
    Flooding?: Array<ForecastRegionDto>;
    Ice?: Array<ForecastRegionDto>;
    EventOnGlacier?: Array<ForecastRegionDto>;
    'Jøkulhaup'?: Array<ForecastRegionDto>;
    Drought?: Array<ForecastRegionDto>;
    Unknown?: Array<ForecastRegionDto>;
}

