/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AreasDtoForecastRegions } from './areas-dto-forecast-regions';
import { CountyDto } from './county-dto';


export interface AreasDto { 
    CountryId?: number;
    CountryName?: string | null;
    CountryDescription?: string | null;
    SortOrder?: number;
    ForecastRegions?: AreasDtoForecastRegions | null;
    Counties?: Array<CountyDto> | null;
}

