/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AreasDtoForecastRegions } from './areas-dto-forecast-regions';
import { CountyDto } from './county-dto';


export interface AreasDto { 
    CountryId: number;
    CountryName?: string;
    CountryDescription?: string;
    SortOrder: number;
    ForecastRegions?: AreasDtoForecastRegions;
    Counties?: Array<CountyDto>;
}

