/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AtAGlanceViewModel { 
    RegId: number;
    GeoHazardTID?: number | null;
    DtObsTime: string;
    NickName?: string;
    CompetenceLevelTID?: number | null;
    Title?: string;
    Latitude: number;
    Longitude: number;
    UtmNorth: number;
    UtmEast: number;
    FormNames?: Array<string>;
    /**
     * Returns first attachement url from the observation or null
     */
    FirstAttachmentUrl?: string;
    /**
     * Count of all attachments
     */
    AttachmentsCount?: number | null;
}

