/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AtAGlanceViewModel { 
    RegId?: number;
    GeoHazardTID?: number | null;
    DtObsTime?: string;
    NickName?: string | null;
    CompetenceLevelTID?: number | null;
    Title?: string | null;
    Latitude?: number;
    Longitude?: number;
    UtmNorth?: number;
    UtmEast?: number;
    FormNames?: Array<string> | null;
    /**
     * Returns first attachement url from the observation or null
     */
    FirstAttachmentUrl?: string | null;
    /**
     * Count of all attachments
     */
    AttachmentsCount?: number | null;
}

