/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentViewModelUrlFormats } from './attachment-view-model-url-formats';


export interface AttachmentViewModel { 
    /**
     * Navn på fotograf.
     */
    Photographer?: string | null;
    /**
     * Rettigheter til bilde.
     */
    Copyright?: string | null;
    /**
     * Hvilken himmelretning peker bilde. Gis i grader slik gitt på kompass. 0 er nord og 90 er øst osv.
     */
    Aspect?: number | null;
    /**
     * Sett naturfare. Tabellen brukes av alle naturfarer (snø, jord, vann, is). The GeoHazardKD unique identifier
     */
    GeoHazardTID?: number | null;
    /**
     * Hva er bildet av. Dette feltet relaterer bildet til en observasjonstype. Feks værobservasjon, faretegn, osv. The RegistrationKD unique identifier
     */
    RegistrationTID?: number | null;
    /**
     * Kommentarfelt for bildet. F.eks for å beskrive det.
     */
    Comment?: string | null;
    AttachmentMimeType?: string | null;
    /**
     * Om bildet skal vises først i registreringen, eller ikke
     */
    IsMainAttachment?: boolean | null;
    AttachmentId: number;
    /**
     * GeoHazard name
     */
    GeoHazardName?: string | null;
    /**
     * Registration name
     */
    RegistrationName?: string | null;
    UrlFormats?: AttachmentViewModelUrlFormats | null;
    /**
     * Full original image url
     */
    Url?: string | null;
    /**
     * If true, the attachment is an image generated from a snow profile plot
     */
    IsSnowProfilePlot: boolean;
}

