/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvalancheObsEditModel { 
    /**
     * Tid da skredet gikk.
     */
    DtAvalancheTime: string;
    /**
     * Tidligste tidspunkt da skredet gikk.
     */
    DtEarliestAvalancheTime?: string | null;
    /**
     * Eksposisjon
     */
    Aspect?: number | null;
    /**
     * Høyde i løsneområde
     */
    HeightStartZone?: number | null;
    /**
     * Høyde i stoppområdet
     */
    HeightStopZone?: number | null;
    /**
     * Størrelse. The DestructiveSizeKD unique identifier
     */
    DestructiveSizeTID?: number | null;
    /**
     * Skredutløser. The AvalancheTriggerKD unique identifier
     */
    AvalancheTriggerTID?: number | null;
    /**
     * Skredtype. The AvalancheKD unique identifier
     */
    AvalancheTID?: number | null;
    /**
     * Terrengtype i løsneområdet. The TerrainStartZoneKD unique identifier
     */
    TerrainStartZoneTID?: number | null;
    /**
     * SnowLine
     */
    SnowLine?: number | null;
    /**
     * ValidExposition
     */
    ValidExposition?: string | null;
    /**
     * Skredutløser. The AvalCauseTID unique identifier
     */
    AvalCauseTID?: number | null;
    /**
     * Bruddhøyde
     */
    FractureHeight?: number | null;
    /**
     * Bruddbredde
     */
    FractureWidth?: number | null;
    /**
     * Skredbanenavn
     */
    Trajectory?: string | null;
    /**
     * StartLat
     */
    StartLat?: number | null;
    /**
     * StartLong
     */
    StartLong?: number | null;
    /**
     * StopLat
     */
    StopLat?: number | null;
    /**
     * StopLong
     */
    StopLong?: number | null;
    /**
     * Ble skredet fjernutløst?
     */
    RemotelyTriggered?: boolean | null;
    /**
     * Hull of avalanche polygon, List(lon, lat)
     */
    Extent?: Array<Array<number>> | null;
    /**
     * Hull of avalanche starting zone, List(lon, lat)
     */
    StartExtent?: Array<Array<number>> | null;
    /**
     * Hull of avalanche runout zone, List (lon, lat)
     */
    StopExtent?: Array<Array<number>> | null;
    /**
     * Comment
     */
    Comment?: string | null;
}

