/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvalancheActivityObsViewModel { 
    /**
     * Unik id på denne tabellen da flere er mulig pr RegID.
     */
    AvalancheActivityObsID?: number;
    /**
     * Hvilken side av fjellene har skredene gått? Gis i grader slik gitt på kompass. 0 er nord og 90 er øst osv.
     */
    Aspect?: number;
    /**
     * Meter over havet på løsneområdet.
     */
    HeigthStartZone?: number;
    /**
     * Når gikk skredene? Her bruker vi feltet som en ca. tid og brukerene oppfordres til å anta best mulig.
     */
    DtAvalancheTime?: string;
    /**
     * Hvor store er skredene?. The DestructiveSizeKD unique identifier
     */
    DestructiveSizeTID?: number | null;
    DestructiveSizeName?: string | null;
    /**
     * Hvor mange skred er gått? The EstimatedNumKD unique identifier
     */
    EstimatedNumTID?: number | null;
    EstimatedNumName?: string | null;
    /**
     * Typen skred som er gått. The AvalancheKD unique identifier
     */
    AvalancheTID?: number | null;
    AvalancheName?: string | null;
    /**
     * Hva utløste skredet? Det er ofte beskrevet som det svake laget i snødekket. The AvalancheTriggerKD unique identifier
     */
    AvalancheTriggerTID?: number | null;
    AvalancheTriggerName?: string | null;
    /**
     * Hva slags terrengtype var det i løsneområdet. The TerrainStartZoneKD unique identifier
     */
    TerrainStartZoneTID?: number | null;
    TerrainStartZoneName?: string | null;
    /**
     * Hvor går snøgrensa i området?
     */
    SnowLine?: number | null;
    SnowLineName?: string | null;
    /**
     * Kommentarfelt for å skrive utfyllende tekst om observasjonen.
     */
    Comment?: string | null;
    DtOffAvalancheTime?: string;
}

