/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';


export interface AvalancheEvaluation2ViewModel { 
    AvalancheDangerName?: string | null;
    ValidExposition?: string | null;
    Comment?: string | null;
    AvalancheEvaluation?: string | null;
    AvalancheDevelopment?: string | null;
    ExposedHeight1?: number | null;
    ExposedHeight2?: number | null;
    ExposedHeightComboTID?: number | null;
    ExposedHeightComboName?: string | null;
    ExposedClimateTID?: number | null;
    ExposedClimateName?: string | null;
    AvalancheDangerTID?: number | null;
    AvalancheEvalProblems?: Array<AvalancheEvalProblemViewModel> | null;
}

