/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvalancheEvaluation3ViewModel { 
    /**
     * Faregrad. The AvalancheDangerKD unique identifier
     */
    AvalancheDangerTID?: number | null;
    /**
     * Her blir Skredfarevurdering skrevet inn. I appen blir “Utstrekning” lagt til som tekst i denne kolonnen
     */
    AvalancheEvaluation?: string | null;
    /**
     * Her blir forventet utvikling skrevet inn.
     */
    AvalancheDevelopment?: string | null;
    /**
     * Felt hvor observatøren kan fortelle de syns varslet stemmer. Valg fra liste gitt i ForecastCorrectKD. The ForecastCorrectKD unique identifier
     */
    ForecastCorrectTID?: number | null;
    /**
     * Kommetarfelt for utdypende kommentar om varslet stemmer eller ikke.
     */
    ForecastComment?: string | null;
    AvalancheDangerName?: string;
    ForecastCorrectName?: string;
}

