/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';


export interface AvalancheEvaluation2ViewModel { 
    AvalancheDangerName?: string;
    ValidExposition?: string;
    Comment?: string;
    AvalancheEvaluation?: string;
    AvalancheDevelopment?: string;
    ExposedHeight1?: number | null;
    ExposedHeight2?: number | null;
    ExposedHeightComboTID?: number | null;
    ExposedHeightComboName?: string;
    ExposedClimateTID?: number | null;
    ExposedClimateName?: string;
    AvalancheDangerTID?: number | null;
    AvalancheEvalProblems?: Array<AvalancheEvalProblemViewModel>;
}

