/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvalancheDangerObsViewModel { 
    AvalancheDangerObsID: number;
    DangerSignTID?: number | null;
    DangerSignName?: string;
    Comment?: string;
}

