/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvalancheDangerObsViewModel { 
    AvalancheDangerObsID?: number;
    DangerSignTID?: number | null;
    DangerSignName?: string | null;
    Comment?: string | null;
}

