/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvalancheActivityObs2ViewModel { 
    EstimatedNumTID?: number | null;
    DtStart?: string | null;
    DtEnd?: string | null;
    ValidExposition?: string | null;
    ExposedHeight1?: number | null;
    ExposedHeight2?: number | null;
    ExposedHeightComboTID?: number | null;
    AvalancheExtTID?: number | null;
    AvalCauseTID?: number | null;
    AvalTriggerSimpleTID?: number | null;
    DestructiveSizeTID?: number | null;
    AvalPropagationTID?: number | null;
    Comment?: string | null;
    EstimatedNumName?: string | null;
    ExposedHeightComboName?: string | null;
    AvalancheExtName?: string | null;
    AvalCauseName?: string | null;
    AvalTriggerSimpleName?: string | null;
    DestructiveSizeName?: string | null;
    AvalPropagationName?: string | null;
}

