/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTripDto { 
    Comment?: string | null;
    DeviceGuid?: string;
    GeoHazardID?: number;
    Lat?: string | null;
    Lng?: string | null;
    ObservationExpectedMinutes?: number;
    TripTypeID?: number;
}

