/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentViewModel } from './attachment-view-model';
import { LatLng } from './lat-lng';


export interface DamageObsViewModel { 
    GeoHazardTID?: number | null;
    DamageTypeTID: number;
    DamagePosition?: LatLng | null;
    Comment?: string | null;
    Attachments?: Array<AttachmentViewModel>;
    GeoHazardName?: string;
    DamageTypeName?: string;
}

