/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentViewModel } from './attachment-view-model';
import { LatLng } from './lat-lng';


export interface DamageObsViewModel { 
    GeoHazardTID?: number | null;
    DamageTypeTID: number;
    DamagePosition?: LatLng | null;
    Comment?: string | null;
    Attachments?: Array<AttachmentViewModel> | null;
    GeoHazardName?: string | null;
    DamageTypeName?: string | null;
}

