/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DangerObsEditModel { 
    /**
     * Sett naturfare. Tabellen brukes av alle naturfarer (snø, jord, vann, is). The GeoHazardKD unique identifier
     */
    GeoHazardTID?: number | null;
    /**
     * Faretegn er listet i tabellen DangerSignKD. The DangerSignKD unique identifier
     */
    DangerSignTID?: number | null;
    /**
     * Kommentarfelt for å skrive utfyllende tekst om faretegnet.
     */
    Comment?: string | null;
}

