/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForecastRegionSubRegionDto } from './forecast-region-sub-region-dto';


export interface ForecastRegionDto { 
    Id: number;
    Text?: string;
    SortOrder: number;
    SubRegions?: Array<ForecastRegionSubRegionDto>;
    IsRegionForGrouping: boolean;
}

