/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForecastRegionSubRegionDto } from './forecast-region-sub-region-dto';


export interface ForecastRegionDto { 
    Id: number;
    Text?: string | null;
    SortOrder: number;
    SubRegions?: Array<ForecastRegionSubRegionDto> | null;
    IsRegionForGrouping: boolean;
}

