/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlEditModel } from './url-edit-model';


export interface GeneralObservationEditModel { 
    /**
     * Sett naturfare. Tabellen brukes av alle naturfarer (snø, jord, vann, is).
     */
    GeoHazardTID?: number | null;
    /**
     * Selve registreringen.
     */
    ObsComment?: string | null;
    /**
     * Overskriften (hovedpoenget).
     */
    ObsHeader?: string | null;
    /**
     * Kommentarfelt for å skrive utfyllende tekst
     */
    Comment?: string | null;
    Urls?: Array<UrlEditModel> | null;
}

