/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * NotSpecified = 0, Avalanche = 10, EarthFlow = 20, LandSlide = 30, RockFall = 40, IceFall = 50, Flooding = 60, Ice = 70, EventOnGlacier = 100, Jøkulhaup = 110, Drought = 200, Unknown = 999
 */
export const GeoHazardTypes = {
    NUMBER_0: 0,
    NUMBER_10: 10,
    NUMBER_20: 20,
    NUMBER_30: 30,
    NUMBER_40: 40,
    NUMBER_50: 50,
    NUMBER_60: 60,
    NUMBER_70: 70,
    NUMBER_100: 100,
    NUMBER_110: 110,
    NUMBER_200: 200,
    NUMBER_999: 999
} as const;
export type GeoHazardTypes = typeof GeoHazardTypes[keyof typeof GeoHazardTypes];

