/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeoLocationInfo { 
    Name?: string | null;
    Municipality?: string | null;
    MunicipalityId?: string | null;
    AdminAreaName?: string | null;
    AdminAreaId?: string | null;
    Country?: string | null;
    CountryCode?: string | null;
    Masl?: number | null;
    Steepness?: number | null;
    WarningRegionId?: string | null;
    WarningRegionName?: string | null;
}

