/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeoLocationSummary { 
    Header?: string | null;
    Lines?: Array<string> | null;
}

