/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeoLocationInfo { 
    Name?: string;
    Municipality?: string;
    MunicipalityId?: string;
    AdminAreaName?: string;
    AdminAreaId?: string;
    Country?: string;
    CountryCode?: string;
    Masl?: number | null;
    Steepness?: number | null;
    WarningRegionId?: string;
    WarningRegionName?: string;
}

