/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IceThicknessLayerEditModel { 
    /**
     * The IceLayerKD unique identifier
     */
    IceLayerTID?: number | null;
    /**
     * IceLayerThickness
     */
    IceLayerThickness?: number | null;
    /**
     * Comment
     */
    Comment?: string | null;
}

