/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlEditModel } from './url-edit-model';


export interface IceCoverEditModel { 
    /**
     * Hvordan har vannet vært isdekt før den aktuelle observajonen? Feks var det isfritt? Feltet sier noe om hvordan utviklingen er. The IceCoverBeforeKD unique identifier
     */
    IceCoverBeforeTID?: number | null;
    /**
     * Hvordan er vannet dekket av is nå. The IceCoverKD unique identifier
     */
    IceCoverTID?: number | null;
    IceCoverAfterTID?: number | null;
    /**
     * Kommentarfelt for å skrive utfyllende tekst om observasjonen.
     */
    Comment?: string | null;
    /**
     * Skøytebarhet. IceSkateabilityKD unique identifier
     */
    IceSkateabilityTID?: number | null;
    /**
     * Bæreevne. IceCapacityKD unique identifier
     */
    IceCapacityTID?: number | null;
    Urls?: Array<UrlEditModel> | null;
}

