/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IceThicknessLayerViewModel } from './ice-thickness-layer-view-model';


export interface IceThicknessViewModel { 
    /**
     * Mengden tørr snø oppå isen. Verdi i meter [m].
     */
    SnowDepth?: number | null;
    /**
     * Mengden sørpe oppå isen. Verdi i meter [m].
     */
    SlushSnow?: number | null;
    /**
     * Total istykkelse. I tabellen IceThicknessLayer kan individuelle islag registreres. Summen av dem skal samsvare med IceThickenssSum. Verdi i meter [m].
     */
    IceThicknessSum?: number | null;
    /**
     * Isen kan være presset under vannspeilet eller flyte oppå. Her registreres denne høyden før borring. IceHeightBefore = 0 betyr at isen er tørr og negative verdier angir overvann. Verdi i meter [m].
     */
    IceHeightBefore?: number | null;
    /**
     * Isen kan være presset under vannspeilet eller flyte oppå. Her registreres denne høyden etter borring. IPositive verdier angir at vannet står nedi hulet og og negative verdier angir overvann. Verdi i meter [m].
     */
    IceHeightAfter?: number | null;
    /**
     * Comment
     */
    Comment?: string | null;
    IceThicknessLayers?: Array<IceThicknessLayerViewModel> | null;
}

