/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlEditModel } from './url-edit-model';


export interface IncidentEditModel { 
    /**
     * Sett naturfare. Tabellen brukes av alle naturfarer (snø, jord, vann, is).
     */
    GeoHazardTID?: number | null;
    /**
     * Hva ble påvirket av hendelsen. Valgene er gitt i ActivityInfluencedKD. The ActivityInfluencedKD unique identifier
     */
    ActivityInfluencedTID?: number | null;
    /**
     * Skadeomfang. Hva var konsekvensen av hendelsen. Valgene gitt i DamageExtentKD. The DamageExtentKD unique identifier
     */
    DamageExtentTID?: number | null;
    /**
     * Var det et varsel utstedt og stemte det? The ForecastAccurateKD unique identifier
     */
    ForecastAccurateTID?: number | null;
    /**
     * Var man lokal, norsk eller utenlandsk turist?
     */
    LocalTouristTID?: number | null;
    /**
     * Hvor ofte er man i området?
     */
    LocalKnowledgeTID?: number | null;
    /**
     * Hvor mange var involvert?
     */
    InvolvedNum?: number | null;
    /**
     * Hvor mange var i skredet/vannet?
     */
    CasualtiesNum?: number | null;
    /**
     * Hvor mange vart skadd?
     */
    HarmedNum?: number | null;
    /**
     * Hvor mange døde?
     */
    DeadNum?: number | null;
    /**
     * Hvor mange evakuerte?
     */
    EvacuatedNum?: number | null;
    /**
     * Er  trafikk hindret?
     */
    TrafficObstructed?: boolean | null;
    /**
     * Er  det noen materielle skader?
     */
    MaterialDamages?: boolean | null;
    /**
     * Var det noe sikkerhetsutstyr i bruk?
     */
    SafetyGearTID?: number | null;
    /**
     * Hvem gjennomførte redningen?
     */
    RescueTID?: number | null;
    /**
     * Hvilken turfase?
     */
    SlopeActivityTID?: number | null;
    /**
     * Om hendelsen strakte seg ut i tid, når sluttet den å gjelde? Feks, når åpnet veien igjen etter raset?
     */
    DtEndTime?: string | null;
    /**
     * Hendelsen beskrives med overskrift ..
     */
    IncidentHeader?: string | null;
    /**
     * .. med ingress eller sammendrag ..
     */
    IncidentIngress?: string | null;
    /**
     * .. og teksten eller artikkelen.
     */
    IncidentText?: string | null;
    /**
     * Comment.
     */
    Comment?: string | null;
    /**
     * Provide description for IncidentURLs
     */
    IncidentURLs?: Array<UrlEditModel>;
}

