/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlViewModel } from './url-view-model';


export interface LandslideViewModel { 
    /**
     * Hva slags type skred er det snakk om? Valg gitt i LandSlideKD. The LandSlideKD unique identifier
     */
    LandSlideTID?: number | null;
    /**
     * Hva utløste skredet? The LandSlideTriggerKD unique identifier
     */
    LandSlideTriggerTID?: number | null;
    /**
     * Hvor stort er skredet? The LandSlideSizeKD unique identifier
     */
    LandSlideSizeTID?: number | null;
    Comment?: string | null;
    /**
     * Spesifiser skredtype. vått jordskred?, jordskred eller steinskred? GeoHazardTID = 20, 30 og 40 er aktuelle. The GeoHazardKD unique identifier
     */
    GeoHazardTID?: number | null;
    /**
     * Hva ble påvirket av hendelsen. Valgene er gitt i ActivityInfluencedKD. The ActivityInfluencedKD unique identifier
     */
    ActivityInfluencedTID?: number | null;
    /**
     * Var det et varsel utstedt og stemte det? The ForecastAccurateKD unique identifier
     */
    ForecastAccurateTID?: number | null;
    /**
     * Skadeomfang. Hva var konsekvensen av hendelsen. Valgene gitt i DamageExtentKD. The DamageExtentKD unique identifier
     */
    DamageExtentTID?: number | null;
    /**
     * Latitude start posisjon
     */
    StartLat?: number | null;
    /**
     * Long start posisjon
     */
    StartLong?: number | null;
    /**
     * Latitude stopp posisjon
     */
    StopLat?: number | null;
    /**
     * Long stopp posisjon
     */
    StopLong?: number | null;
    /**
     * Hull of avalanche polygon, List(lon, lat)
     */
    Extent?: Array<Array<number>> | null;
    /**
     * Hull of avalanche starting zone, List(lon, lat)
     */
    StartExtent?: Array<Array<number>> | null;
    /**
     * Hull of avalanche runout zone, List(lon, lat)
     */
    StopExtent?: Array<Array<number>> | null;
    /**
     * Når gikk skredet? Dette er ikke det samme tidspunktet da skredet ble observert.
     */
    DtLandSlideTime: string;
    /**
     * Når stoppet skredet?
     */
    DtLandSlideTimeEnd?: string | null;
    Urls?: Array<UrlViewModel> | null;
    LandSlideName?: string | null;
    LandSlideTriggerName?: string | null;
    LandSlideSizeName?: string | null;
    GeoHazardName?: string | null;
    ActivityInfluencedName?: string | null;
    ForecastAccurateName?: string | null;
    DamageExtentName?: string | null;
}

