/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverGroupDto } from './observer-group-dto';
import { ObserverCompetenceDto } from './observer-competence-dto';


export interface MyPageData { 
    Guid?: string;
    /**
     * Returns unique id that identifies an observer
     */
    ObserverId?: number;
    NickName?: string | null;
    Email?: string | null;
    MobPhoneNr?: string | null;
    FirstName?: string | null;
    LastName?: string | null;
    WorkPlace?: string | null;
    Adrnr?: number | null;
    DtRegTime?: string | null;
    MemberOfGroups?: Array<ObserverGroupDto> | null;
    PendingInvitationsToGroups?: Array<ObserverGroupDto> | null;
    Competence?: Array<ObserverCompetenceDto> | null;
    NumberOfObservations?: number;
    MainGeohazardTID?: number;
    LastRegistrationDate?: string | null;
    DefaultMunicipality?: string | null;
    Roles?: Array<string> | null;
}

