/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverGroupDto } from './observer-group-dto';
import { ObserverCompetenceDto } from './observer-competence-dto';


export interface MyPageData { 
    Guid: string;
    /**
     * Returns unique id that identifies an observer
     */
    ObserverId: number;
    NickName?: string;
    Email?: string;
    MobPhoneNr?: string;
    FirstName?: string;
    LastName?: string;
    WorkPlace?: string;
    Adrnr?: number | null;
    DtRegTime?: string | null;
    MemberOfGroups?: Array<ObserverGroupDto>;
    PendingInvitationsToGroups?: Array<ObserverGroupDto>;
    Competence?: Array<ObserverCompetenceDto>;
    NumberOfObservations: number;
    MainGeohazardTID: number;
    LastRegistrationDate?: string | null;
    DefaultMunicipality?: string;
    Roles?: Array<string>;
}

