/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObsLocationEditModel { 
    /**
     * ObsLocationID
     */
    ObsLocationID?: number | null;
    /**
     * Navn på stedet
     */
    LocationName?: string | null;
    /**
     * Beskriver stedet.
     */
    LocationDescription?: string | null;
    /**
     * Latitude
     */
    Latitude: number;
    /**
     * Longitude
     */
    Longitude: number;
    /**
     * Kildehenvisning på hvordan koordinaten er satt. (GPS i tlf, klikk i kart, osv). Verdier gitt i UTMSourceKD
     */
    UTMSourceTID?: number | null;
    /**
     * Usikkerhet i posisjon i meter. Anslås på web og i app hentes det fra gps.
     */
    Uncertainty?: number | null;
}

