/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LatLngObject } from './lat-lng-object';


export interface ObsLocationsResponseDtoV2 { 
    Name?: string;
    Id: number;
    Distance: number;
    LatLngObject?: LatLngObject;
    ObserverNickName?: string;
    ObserverGroupName?: string;
    ObserverGroupId?: number | null;
    LocationDescription?: string;
    GeoHazardId?: number | null;
}

