/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LatLngObject } from './lat-lng-object';


export interface ObsLocationsResponseDtoV2 { 
    Name?: string | null;
    Id: number;
    Distance: number;
    LatLngObject?: LatLngObject | null;
    ObserverNickName?: string | null;
    ObserverGroupName?: string | null;
    ObserverGroupId?: number | null;
    LocationDescription?: string | null;
    GeoHazardId?: number | null;
}

