/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObsLocationViewModel { 
    ObsLocationID: number;
    /**
     * Navn på stedet
     */
    LocationName?: string | null;
    /**
     * Beskriver stedet.
     */
    LocationDescription?: string | null;
    /**
     * Latitude
     */
    Latitude: number;
    /**
     * Longitude
     */
    Longitude: number;
    /**
     * Kildehenvisning på hvordan koordinaten er satt. (GPS i tlf, klikk i kart, osv). Verdier gitt i UTMSourceKD
     */
    UTMSourceTID: number;
    UTMSourceName?: string | null;
    /**
     * Usikkerhet i posisjon i meter. Anslås på web og i app hentes det fra gps.
     */
    Uncertainty?: number | null;
    /**
     * Anngir varslingsregion stedet tilhører. Varslingsregioner gitt i ForecastRegionKD. The ForecastRegionKD unique identifier
     */
    ForecastRegionTID?: number | null;
    ForecastRegionName?: string | null;
    Height?: number | null;
    MunicipalName?: string | null;
    /**
     * Kommune nr stedet tilhører
     */
    MunicipalNo?: string | null;
    CountryId?: number | null;
    CountryName?: string | null;
    /**
     * Read-only generert tittel
     */
    Title?: string | null;
}

