/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverGroupDto } from './observer-group-dto';


export interface ObserverResponseDto { 
    Guid: string;
    ObserverGroup?: Array<ObserverGroupDto> | null;
    Nick?: string | null;
}

