/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverGroupDto } from './observer-group-dto';


export interface ObserverResponseDto { 
    Guid: string;
    ObserverGroup?: Array<ObserverGroupDto>;
    Nick?: string;
}

