/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObserverGroupDto { 
    Id: number;
    Name?: string;
    ObserverGroupDescription?: string;
    WorkPlace?: string;
    Comment?: string;
}

