/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Operator } from './operator';


/**
 * Filter by property value
 */
export interface PropertyFilter { 
    /**
     * Property name. Properties in sub schemas must be prefixed with schema name. Example: AvalancheObs.AvalancheTID Multiple instance schemas, like DangerSign, are not supported. If you use unknown/unsupported properties, you will get an HTTP 400.
     */
    Name?: string | null;
    Operator: Operator;
    /**
     * Target property value
     */
    Value?: string | null;
}
export namespace PropertyFilter {
}


