/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueKind } from './value-kind';


export interface RegObsGenericValue { 
    Kind: ValueKind;
    readonly KindType?: string | null;
    Header?: string | null;
    Value?: any | null;
}
export namespace RegObsGenericValue {
}


