/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Waterlevel2EditModel } from './waterlevel2-edit-model';
import { DangerObsEditModel } from './danger-obs-edit-model';
import { AvalancheEvalProblem2EditModel } from './avalanche-eval-problem2-edit-model';
import { SnowProfileEditModel } from './snow-profile-edit-model';
import { GeoHazardTypes } from './geo-hazard-types';
import { LandslideEditModel } from './landslide-edit-model';
import { AvalancheActivityObs2EditModel } from './avalanche-activity-obs2-edit-model';
import { AttachmentEditModel } from './attachment-edit-model';
import { DamageObsEditModel } from './damage-obs-edit-model';
import { IceThicknessEditModel } from './ice-thickness-edit-model';
import { IncidentEditModel } from './incident-edit-model';
import { WeatherEditModel } from './weather-edit-model';
import { SnowSurfaceEditModel } from './snow-surface-edit-model';
import { ObsLocationEditModel } from './obs-location-edit-model';
import { AvalancheObsEditModel } from './avalanche-obs-edit-model';
import { CompressionTestEditModel } from './compression-test-edit-model';
import { GeneralObservationEditModel } from './general-observation-edit-model';
import { IceCoverEditModel } from './ice-cover-edit-model';
import { AvalancheEvaluation3EditModel } from './avalanche-evaluation3-edit-model';


export interface RegistrationEditModel { 
    /**
     * Sett naturfare. Tabellen brukes av alle naturfarer (snø, jord, vann, is). The GeoHazardKD unique identifier
     */
    GeoHazardTID: GeoHazardTypes;
    /**
     * Kildereferanse på en registrering. F.eks. har brukeren sette dette selv eller er det referert til fra nyheter. The SourceKD unique identifier
     */
    SourceTID?: number | null;
    /**
     * Tiden da observasjonen ble gjort.
     */
    DtObsTime: string;
    DtChangeTime?: string | null;
    ObserverGroupID?: number | null;
    ObserverGroupName?: string | null;
    /**
     * If set to true, the user\'s account will not be shown publicly. NVE will still be able to see who sent in the observation.
     */
    Anonymous?: boolean | null;
    /**
     * The observation location object. Latitude and longitute are needed to create a new registration.
     */
    ObsLocation?: ObsLocationEditModel;
    Attachments?: Array<AttachmentEditModel>;
    AvalancheActivityObs2?: Array<AvalancheActivityObs2EditModel>;
    AvalancheEvalProblem2?: Array<AvalancheEvalProblem2EditModel>;
    AvalancheEvaluation3?: AvalancheEvaluation3EditModel | null;
    AvalancheObs?: AvalancheObsEditModel | null;
    CompressionTest?: Array<CompressionTestEditModel>;
    DangerObs?: Array<DangerObsEditModel>;
    GeneralObservation?: GeneralObservationEditModel | null;
    IceCoverObs?: IceCoverEditModel | null;
    IceThickness?: IceThicknessEditModel | null;
    Incident?: IncidentEditModel | null;
    LandSlideObs?: LandslideEditModel | null;
    SnowProfile2?: SnowProfileEditModel | null;
    SnowSurfaceObservation?: SnowSurfaceEditModel | null;
    WeatherObservation?: WeatherEditModel | null;
    WaterLevel2?: Waterlevel2EditModel | null;
    DamageObs?: Array<DamageObsEditModel>;
}
export namespace RegistrationEditModel {
}


