/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentViewModel } from './attachment-view-model';


export interface RegistrationsWithAttachments { 
    /**
     * Unique registration id that contains attachments
     */
    RegId: number;
    /**
     * List of registration\'s attachments
     */
    Attachments?: Array<AttachmentViewModel>;
}

