/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IceThicknessViewModel } from './ice-thickness-view-model';
import { SnowSurfaceViewModel } from './snow-surface-view-model';
import { IncidentViewModel } from './incident-view-model';
import { ObserverViewModel } from './observer-view-model';
import { GeoHazardTypes } from './geo-hazard-types';
import { WeatherViewModel } from './weather-view-model';
import { DamageObsViewModel } from './damage-obs-view-model';
import { LandslideViewModel } from './landslide-view-model';
import { WaterLevelViewModel } from './water-level-view-model';
import { SnowProfileViewModel } from './snow-profile-view-model';
import { AvalancheObsViewModel } from './avalanche-obs-view-model';
import { AvalancheActivityObsViewModel } from './avalanche-activity-obs-view-model';
import { AvalancheDangerObsViewModel } from './avalanche-danger-obs-view-model';
import { SnowCoverObsViewModel } from './snow-cover-obs-view-model';
import { AvalancheEvaluation3ViewModel } from './avalanche-evaluation3-view-model';
import { CompressionTestViewModel } from './compression-test-view-model';
import { IceCoverViewModel } from './ice-cover-view-model';
import { AvalancheEvaluationViewModel } from './avalanche-evaluation-view-model';
import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';
import { ObsLocationViewModel } from './obs-location-view-model';
import { AvalancheActivityObs2ViewModel } from './avalanche-activity-obs2-view-model';
import { AttachmentViewModel } from './attachment-view-model';
import { Waterlevel2ViewModel } from './waterlevel2-view-model';
import { DangerObsViewModel } from './danger-obs-view-model';
import { AvalancheEvaluation2ViewModel } from './avalanche-evaluation2-view-model';
import { AvalancheEvalProblem2ViewModel } from './avalanche-eval-problem2-view-model';
import { Summary } from './summary';
import { GeneralObservationViewModel } from './general-observation-view-model';


export interface RegistrationViewModel { 
    RegId: number;
    /**
     * NotSpecified = 0, Avalanche = 10, EarthFlow = 20, LandSlide = 30, RockFall = 40, IceFall = 50, Flooding = 60, Ice = 70, EventOnGlacier = 100, Jøkulhaup = 110, Drought = 200, Unknown = 999
     */
    GeoHazardTID: GeoHazardTypes;
    SourceTID: number;
    DtObsTime: string;
    DtChangeTime?: string | null;
    ObserverGroupID?: number | null;
    ObserverGroupName?: string | null;
    Anonymous?: boolean | null;
    ExternalReferenceId?: string | null;
    GeoHazardName?: string;
    DtRegTime: string;
    SourceName?: string;
    Observer: ObserverViewModel;
    ObsLocation: ObsLocationViewModel;
    Attachments?: Array<AttachmentViewModel>;
    AvalancheActivityObs2?: Array<AvalancheActivityObs2ViewModel> | null;
    AvalancheEvalProblem2?: Array<AvalancheEvalProblem2ViewModel> | null;
    AvalancheEvaluation3?: AvalancheEvaluation3ViewModel | null;
    AvalancheObs?: AvalancheObsViewModel | null;
    CompressionTest?: Array<CompressionTestViewModel> | null;
    DangerObs?: Array<DangerObsViewModel> | null;
    GeneralObservation?: GeneralObservationViewModel | null;
    IceCoverObs?: IceCoverViewModel | null;
    IceThickness?: IceThicknessViewModel | null;
    Incident?: IncidentViewModel | null;
    LandSlideObs?: LandslideViewModel | null;
    SnowProfile2?: SnowProfileViewModel | null;
    SnowSurfaceObservation?: SnowSurfaceViewModel | null;
    WeatherObservation?: WeatherViewModel | null;
    WaterLevel2?: Waterlevel2ViewModel | null;
    DamageObs?: Array<DamageObsViewModel> | null;
    Summaries?: Array<Summary>;
    AttachmentSummaries?: Array<Summary> | null;
    SnowProfile?: AttachmentViewModel | null;
    AvalancheEvaluation?: AvalancheEvaluationViewModel | null;
    AvalancheActivityObs?: Array<AvalancheActivityObsViewModel> | null;
    AvalancheDangerObs?: Array<AvalancheDangerObsViewModel> | null;
    AvalancheEvalProblem?: Array<AvalancheEvalProblemViewModel> | null;
    AvalancheEvaluation2?: AvalancheEvaluation2ViewModel | null;
    SnowCoverObs?: SnowCoverObsViewModel | null;
    WaterLevel?: WaterLevelViewModel | null;
}
export namespace RegistrationViewModel {
}


