/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IceThicknessViewModel } from './ice-thickness-view-model';
import { SnowSurfaceViewModel } from './snow-surface-view-model';
import { IncidentViewModel } from './incident-view-model';
import { ObserverViewModel } from './observer-view-model';
import { GeoHazardTypes } from './geo-hazard-types';
import { WeatherViewModel } from './weather-view-model';
import { DamageObsViewModel } from './damage-obs-view-model';
import { LandslideViewModel } from './landslide-view-model';
import { WaterLevelViewModel } from './water-level-view-model';
import { SnowProfileViewModel } from './snow-profile-view-model';
import { AvalancheObsViewModel } from './avalanche-obs-view-model';
import { AvalancheActivityObsViewModel } from './avalanche-activity-obs-view-model';
import { AvalancheDangerObsViewModel } from './avalanche-danger-obs-view-model';
import { SnowCoverObsViewModel } from './snow-cover-obs-view-model';
import { AvalancheEvaluation3ViewModel } from './avalanche-evaluation3-view-model';
import { CompressionTestViewModel } from './compression-test-view-model';
import { IceCoverViewModel } from './ice-cover-view-model';
import { AvalancheEvaluationViewModel } from './avalanche-evaluation-view-model';
import { AvalancheEvalProblemViewModel } from './avalanche-eval-problem-view-model';
import { ObsLocationViewModel } from './obs-location-view-model';
import { AvalancheActivityObs2ViewModel } from './avalanche-activity-obs2-view-model';
import { AttachmentViewModel } from './attachment-view-model';
import { Waterlevel2ViewModel } from './waterlevel2-view-model';
import { DangerObsViewModel } from './danger-obs-view-model';
import { AvalancheEvaluation2ViewModel } from './avalanche-evaluation2-view-model';
import { AvalancheEvalProblem2ViewModel } from './avalanche-eval-problem2-view-model';
import { Summary } from './summary';
import { GeneralObservationViewModel } from './general-observation-view-model';


export interface RegistrationViewModel { 
    /**
     * Sett naturfare. Tabellen brukes av alle naturfarer (snø, jord, vann, is). The GeoHazardKD unique identifier
     */
    GeoHazardTID: GeoHazardTypes;
    /**
     * Kildereferanse på en registrering. F.eks. har brukeren sette dette selv eller er det referert til fra nyheter. The SourceKD unique identifier
     */
    SourceTID?: number | null;
    /**
     * Tiden da observasjonen ble gjort.
     */
    DtObsTime: string;
    ObserverGroupID?: number | null;
    ObserverGroupName?: string | null;
    /**
     * If set to true, the user\'s account will not be shown publicly. NVE will still be able to see who sent in the observation.
     */
    Anonymous?: boolean | null;
    RegId: number;
    /**
     * Ekstern referanse ID. Må være unik for Applikasjon.
     */
    ExternalReferenceId?: string | null;
    GeoHazardName?: string | null;
    /**
     * Timestamp for registrert i systemet. (Read-Only)
     */
    DtRegTime?: string | null;
    /**
     * Timestamp for endret i systemet. (Read-Only)
     */
    DtChangeTime?: string | null;
    SourceName?: string | null;
    Observer?: ObserverViewModel | null;
    ObsLocation?: ObsLocationViewModel | null;
    Attachments?: Array<AttachmentViewModel> | null;
    AvalancheActivityObs2?: Array<AvalancheActivityObs2ViewModel> | null;
    AvalancheEvalProblem2?: Array<AvalancheEvalProblem2ViewModel> | null;
    AvalancheEvaluation3?: AvalancheEvaluation3ViewModel | null;
    AvalancheObs?: AvalancheObsViewModel | null;
    CompressionTest?: Array<CompressionTestViewModel> | null;
    DangerObs?: Array<DangerObsViewModel> | null;
    GeneralObservation?: GeneralObservationViewModel | null;
    IceCoverObs?: IceCoverViewModel | null;
    IceThickness?: IceThicknessViewModel | null;
    Incident?: IncidentViewModel | null;
    LandSlideObs?: LandslideViewModel | null;
    SnowProfile2?: SnowProfileViewModel | null;
    SnowSurfaceObservation?: SnowSurfaceViewModel | null;
    WeatherObservation?: WeatherViewModel | null;
    WaterLevel2?: Waterlevel2ViewModel | null;
    DamageObs?: Array<DamageObsViewModel> | null;
    Summaries?: Array<Summary> | null;
    AttachmentSummaries?: Array<Summary> | null;
    SnowProfile?: AttachmentViewModel | null;
    AvalancheEvaluation?: AvalancheEvaluationViewModel | null;
    AvalancheActivityObs?: Array<AvalancheActivityObsViewModel> | null;
    AvalancheDangerObs?: Array<AvalancheDangerObsViewModel> | null;
    AvalancheEvalProblem?: Array<AvalancheEvalProblemViewModel> | null;
    AvalancheEvaluation2?: AvalancheEvaluation2ViewModel | null;
    SnowCoverObs?: SnowCoverObsViewModel | null;
    WaterLevel?: WaterLevelViewModel | null;
}
export namespace RegistrationViewModel {
}


