/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationTypeSubTypeDto } from './registration-type-sub-type-dto';


export interface RegistrationTypeDto { 
    Id: number;
    Name?: string | null;
    SubTypes?: Array<RegistrationTypeSubTypeDto> | null;
    SortOrder: number;
}

