/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationTypeDto } from './registration-type-dto';


export interface SearchSideBarDtoRegistrationTypes { 
    NotSpecified?: Array<RegistrationTypeDto>;
    Avalanche?: Array<RegistrationTypeDto>;
    EarthFlow?: Array<RegistrationTypeDto>;
    LandSlide?: Array<RegistrationTypeDto>;
    RockFall?: Array<RegistrationTypeDto>;
    IceFall?: Array<RegistrationTypeDto>;
    Flooding?: Array<RegistrationTypeDto>;
    Ice?: Array<RegistrationTypeDto>;
    EventOnGlacier?: Array<RegistrationTypeDto>;
    'Jøkulhaup'?: Array<RegistrationTypeDto>;
    Drought?: Array<RegistrationTypeDto>;
    Unknown?: Array<RegistrationTypeDto>;
}

