/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AreasDto } from './areas-dto';
import { SearchSideBarDtoObserverCompetenceLevels } from './search-side-bar-dto-observer-competence-levels';
import { SearchSideBarDtoRegistrationTypes } from './search-side-bar-dto-registration-types';


export interface SearchSideBarDto { 
    RegistrationTypes?: SearchSideBarDtoRegistrationTypes | null;
    ObserverCompetenceLevels?: SearchSideBarDtoObserverCompetenceLevels | null;
    Areas?: Array<AreasDto> | null;
}

