/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AreasDto } from './areas-dto';
import { SearchSideBarDtoObserverCompetenceLevels } from './search-side-bar-dto-observer-competence-levels';
import { SearchSideBarDtoRegistrationTypes } from './search-side-bar-dto-registration-types';


export interface SearchSideBarDto { 
    RegistrationTypes?: SearchSideBarDtoRegistrationTypes;
    ObserverCompetenceLevels?: SearchSideBarDtoObserverCompetenceLevels;
    Areas?: Array<AreasDto>;
}

