/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationTypeCriteriaDto } from './registration-type-criteria-dto';
import { WithinRadiusCriteriaDto } from './within-radius-criteria-dto';
import { PropertyFilter } from './property-filter';
import { WithinExtentCriteriaDto } from './within-extent-criteria-dto';


/**
 * Use this to filter out registrations.
 */
export interface SearchCriteriaExclUserRequestDto { 
    /**
     * Find a registration with a specific unique ID. You may also use GET /Registration/{regId}/{langKey}
     */
    RegId?: number | null;
    /**
     * Language of result  Norwegian = 1, English = 2, German = 3, Slovenian = 4, Swedish = 5, Italian = 6, Norwegian (nn) = 7.  Default = 1
     */
    LangKey?: number | null;
    LocationId?: number | null;
    /**
     * Find registrations with obervation time after given date and time (inclusive)
     */
    FromDtObsTime?: string | null;
    /**
     * Find registrations with obervation time before given date and time (inclusive)
     */
    ToDtObsTime?: string | null;
    /**
     * Find registrations saved or changed after given date and time (inclusive)
     */
    FromDtChangeTime?: string | null;
    /**
     * Find registrations saved or changed before given date and time (inclusive)
     */
    ToDtChangeTime?: string | null;
    /**
     * Max number of registrations to return. Default = 100
     */
    NumberOfRecords?: number | null;
    /**
     * Start index. If more registrations matches your filter than you get in one chunk, set Offset to the count of how many records you already fetched, to retrieve the next chunk
     */
    Offset?: number | null;
    TimeZone?: string | null;
    /**
     * Find registrations of given types.  Use /Search/SearchCriteria to find out which types are used for different geo hazards.
     */
    SelectedRegistrationTypes?: Array<RegistrationTypeCriteriaDto> | null;
    /**
     * Find registrations in given regions.  Use /Search/SearchCriteria to find the forecast region IDs that are used for different geo hazards.
     */
    SelectedRegions?: Array<number> | null;
    /**
     * Find registrations on given geo hazard ID\'s.  Snow = 10, soil = 20, water = 60, ice = 70.
     */
    SelectedGeoHazards?: Array<number> | null;
    Countries?: Array<number> | null;
    /**
     * Find registrations in given county.  Only relevant for Norway.  Current valid county numbers are here (from 2024): https://no.wikipedia.org/wiki/Fylkesnummer
     */
    Counties?: Array<string> | null;
    TextSearch?: string | null;
    Radius?: WithinRadiusCriteriaDto | null;
    Extent?: WithinExtentCriteriaDto | null;
    /**
     * Find registrations with given property value.  [Obsolete(\"Experimental feature that may be changed or removed in later versions\")]
     */
    PropertyFilters?: Array<PropertyFilter> | null;
    /**
     * Field to order by. You may use these fields: DtObsTime, DtRegTime, DtChangeTime. Default is DtObsTime. A few other fields may also work
     */
    OrderBy?: string | null;
    /**
     * Descending order is default. Set this to true to use ascending order.
     */
    AscendingOrder?: boolean;
}

