/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoHazardTypes } from './geo-hazard-types';
import { LangKey } from './lang-key';


export interface SearchSideBarRequestDto { 
    /**
     * Snow = 10, dirt = 20, water = 60, ice = 70.  At least one geo hazard is required.
     */
    GeoHazards?: Array<GeoHazardTypes> | null;
    /**
     * NO = 1, EN = 2, DE = 3, SL = 4, SV = 5, IT = 6  Default = 2.
     */
    LangKey?: LangKey;
}
export namespace SearchSideBarRequestDto {
}


