/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverCompetenceLevelDto } from './observer-competence-level-dto';


export interface SearchSideBarDtoObserverCompetenceLevels { 
    NotSpecified?: Array<ObserverCompetenceLevelDto>;
    Avalanche?: Array<ObserverCompetenceLevelDto>;
    EarthFlow?: Array<ObserverCompetenceLevelDto>;
    LandSlide?: Array<ObserverCompetenceLevelDto>;
    RockFall?: Array<ObserverCompetenceLevelDto>;
    IceFall?: Array<ObserverCompetenceLevelDto>;
    Flooding?: Array<ObserverCompetenceLevelDto>;
    Ice?: Array<ObserverCompetenceLevelDto>;
    EventOnGlacier?: Array<ObserverCompetenceLevelDto>;
    'Jøkulhaup'?: Array<ObserverCompetenceLevelDto>;
    Drought?: Array<ObserverCompetenceLevelDto>;
    Unknown?: Array<ObserverCompetenceLevelDto>;
}

