/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SnowSurfaceViewModel { 
    /**
     * Total snødybde i cm. Vi ønsker et gjennomsnitt for området.
     */
    SnowDepth?: number | null;
    /**
     * Nysnødybde i cm. Vi ønsker et gjennomsnitt for området
     */
    NewSnowDepth24?: number | null;
    /**
     * Nysnøgrensa. Hvor faller nedbør som snø? Meter over havet.
     */
    NewSnowLine?: number | null;
    /**
     * Overflatefuktighet
     */
    SurfaceWaterContentTID?: number | null;
    /**
     * Hvor mye har vinden transportert snøen? Valg fra nedtrekksmeny. The SnowDriftKD unique identifier
     */
    SnowDriftTID?: number | null;
    /**
     * Snødekkehardhet
     */
    SnowSurfaceTID?: number | null;
    /**
     * Kommentarfelt for å skrive utfyllende tekst om observasjonen.
     */
    Comment?: string | null;
    /**
     * Grense lagdelt snø (moh)
     */
    HeightLimitLayeredSnow?: number | null;
    /**
     * Snøgrense (moh)
     */
    SnowLine?: number | null;
    /**
     * Obsolete - Only in View Model
     */
    SnowWindDepth24?: number | null;
    SurfaceWaterContentName?: string;
    SnowDriftName?: string;
    SnowSurfaceName?: string;
    SkiConditionsTID?: number | null;
    SkiConditionsName?: string;
    /**
     * Obsolete - Only in View Model
     */
    SurfaceRougnessTID?: number | null;
    SurfaceRougnessName?: string;
    /**
     * Obsolete - Only in View Model
     */
    FootPenetration?: number | null;
}

