/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SnowCoverObsViewModel { 
    /**
     * DepthHoarThickness
     */
    DepthHoarThickness?: number | null;
    /**
     * CriticalLayerExists
     */
    CriticalLayerExists?: boolean | null;
    /**
     * CriticalLayerLocation
     */
    CriticalLayerLocation?: number | null;
    /**
     * The CriticalLayerKD unique identifier
     */
    CriticalLayerTID?: number | null;
    /**
     * SnowPilotRef
     */
    SnowPilotRef?: string | null;
    /**
     * Comment.
     */
    Comment?: string | null;
    CriticalLayerName?: string | null;
}

