/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SnowDensityModel } from './snow-density-model';
import { StratProfileEditModel } from './strat-profile-edit-model';
import { SnowTempModel } from './snow-temp-model';


export interface SnowProfileEditModel { 
    Comment?: string | null;
    IsProfileToGround?: boolean | null;
    Exposition?: number | null;
    SlopeAngle?: number | null;
    SnowTemp?: SnowTempModel | null;
    SnowDensity?: Array<SnowDensityModel> | null;
    StratProfile?: StratProfileEditModel | null;
}

