/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SnowDensityLayerModel } from './snow-density-layer-model';


export interface SnowDensityModel { 
    CylinderDiameter?: number | null;
    TareWeight?: number | null;
    Comment?: string | null;
    Layers?: Array<SnowDensityLayerModel>;
}

