/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SnowDensityLayerModel } from './snow-density-layer-model';


export interface SnowDensityModel { 
    CylinderDiameter?: number | null;
    TareWeight?: number | null;
    Comment?: string | null;
    Layers?: Array<SnowDensityLayerModel> | null;
}

