/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SnowDensityModel } from './snow-density-model';
import { StratProfileViewModel } from './strat-profile-view-model';
import { AttachmentViewModel } from './attachment-view-model';
import { SnowTempModel } from './snow-temp-model';


export interface SnowProfileViewModel { 
    Comment?: string | null;
    IsProfileToGround?: boolean | null;
    Exposition?: number | null;
    SlopeAngle?: number | null;
    SnowTemp?: SnowTempModel | null;
    SnowDensity?: Array<SnowDensityModel>;
    StratProfile?: StratProfileViewModel;
    TotalDepth: number;
    /**
     * Urls to simplified images of the snow profile model
     */
    PlotImage?: AttachmentViewModel;
}

