/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SnowDensityLayerModel { 
    Depth?: number | null;
    /**
     * thickness in m
     */
    Thickness?: number | null;
    /**
     * Density in kg/m^3
     */
    Density?: number | null;
    Comment?: string | null;
    /**
     * Weight in KG
     */
    Weight: number;
    WaterEquivalent: number;
    SortOrder: number;
}

