/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StratProfileLayerEditModel } from './strat-profile-layer-edit-model';


export interface StratProfileEditModel { 
    Layers?: Array<StratProfileLayerEditModel> | null;
}

