/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StratProfileLayerViewModel { 
    DepthTop?: number | null;
    Thickness?: number | null;
    GrainFormPrimaryTID?: number | null;
    GrainFormSecondaryTID?: number | null;
    GrainSizeAvg?: number | null;
    GrainSizeAvgMax?: number | null;
    HardnessTID?: number | null;
    HardnessBottomTID?: number | null;
    WetnessTID?: number | null;
    CriticalLayerTID?: number | null;
    Comment?: string | null;
    SortOrder: number;
    GrainFormPrimaryTName?: string;
    GrainFormSecondaryTName?: string;
    HardnessTName?: string;
    HardnessBottomTName?: string;
    WetnessTName?: string;
    CriticalLayerTName?: string;
}

