/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegObsGenericValue } from './reg-obs-generic-value';


export interface Summary { 
    RegistrationTID?: number;
    RegistrationName?: string | null;
    Summaries?: Array<RegObsGenericValue> | null;
}

