/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentViewModel } from './attachment-view-model';


export interface WaterLevelMeasurementViewModel { 
    WaterLevelMeasurementId?: number;
    WaterLevelValue?: number | null;
    DtMeasurementTime: string;
    Comment?: string | null;
    Attachments?: Array<AttachmentViewModel> | null;
}

