/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaterLevelMeasurementViewModel } from './water-level-measurement-view-model';


export interface Waterlevel2ViewModel { 
    WaterAstrayTID?: number | null;
    ObservationTimingTID?: number | null;
    MeasurementReferenceTID?: number | null;
    MeasurementTypeTID?: number | null;
    WaterLevelMethodTID?: number | null;
    MarkingReferenceTID?: number | null;
    WaterLevelStateTID?: number | null;
    MarkingTypeTID?: number | null;
    MeasuringToolDescription?: string | null;
    WaterLevelMeasurement?: Array<WaterLevelMeasurementViewModel> | null;
    Comment?: string | null;
    WaterLevelStateName?: string | null;
    WaterAstrayName?: string | null;
    ObservationTimingName?: string | null;
    MeasurementReferenceName?: string | null;
    MeasurementTypeName?: string | null;
    WaterLevelMethodName?: string | null;
    MarkingReferenceName?: string | null;
    MarkingTypeName?: string | null;
    /**
     * Flood polygon area, List(lon, lat)
     */
    Extent?: Array<Array<number>> | null;
}

