/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WaterLevelViewModel { 
    WaterLevelDescribed?: string;
    WaterLevelValue?: number | null;
    WaterLevelRefTID: number;
    WaterLevelRefName?: string;
    Comment?: string;
    MeasuredDischarge?: number | null;
    IsRiver: boolean;
}

