/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WaterLevelViewModel { 
    WaterLevelDescribed?: string | null;
    WaterLevelValue?: number | null;
    WaterLevelRefTID?: number;
    WaterLevelRefName?: string | null;
    Comment?: string | null;
    MeasuredDischarge?: number | null;
    IsRiver?: boolean;
}

