/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaterLevelMeasurementEditModel } from './water-level-measurement-edit-model';


export interface Waterlevel2EditModel { 
    WaterAstrayTID?: number | null;
    ObservationTimingTID?: number | null;
    MeasurementReferenceTID?: number | null;
    MeasurementTypeTID?: number | null;
    WaterLevelMethodTID?: number | null;
    MarkingReferenceTID?: number | null;
    WaterLevelStateTID?: number | null;
    MarkingTypeTID?: number | null;
    MeasuringToolDescription?: string | null;
    WaterLevelMeasurement?: Array<WaterLevelMeasurementEditModel>;
    /**
     * Flood polygon area, List(lon, lat)
     */
    Extent?: Array<Array<number>> | null;
    Comment?: string | null;
}

