/**
 * RegObs API, build: 20251103.5 - commit: 62e967e0
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentEditModel } from './attachment-edit-model';


export interface WaterLevelMeasurementEditModel { 
    WaterLevelMeasurementId?: number | null;
    WaterLevelValue?: number | null;
    DtMeasurementTime: string;
    Comment?: string | null;
    Attachments?: Array<AttachmentEditModel> | null;
}

