/**
 * RegObs API, build: Local build - commit: ec80925f
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaterLevelMeasurementViewModel } from './water-level-measurement-view-model';


export interface Waterlevel2ViewModel { 
    WaterAstrayTID?: number | null;
    ObservationTimingTID?: number | null;
    MeasurementReferenceTID?: number | null;
    MeasurementTypeTID?: number | null;
    WaterLevelMethodTID?: number | null;
    MarkingReferenceTID?: number | null;
    WaterLevelStateTID?: number | null;
    MarkingTypeTID?: number | null;
    MeasuringToolDescription?: string | null;
    WaterLevelMeasurement?: Array<WaterLevelMeasurementViewModel>;
    Comment?: string | null;
    WaterLevelStateName?: string;
    WaterAstrayName?: string;
    ObservationTimingName?: string;
    MeasurementReferenceName?: string;
    MeasurementTypeName?: string;
    WaterLevelMethodName?: string;
    MarkingReferenceName?: string;
    MarkingTypeName?: string;
    /**
     * Flood polygon area, List(lon, lat)
     */
    Extent?: Array<Array<number>>;
}

