/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WeatherViewModel { 
    PrecipitationTID?: number | null;
    AirTemperature?: number | null;
    WindSpeed?: number | null;
    WindDirection?: number | null;
    CloudCover?: number | null;
    Comment?: string | null;
    PrecipitationName?: string | null;
    WindDirectionName?: string | null;
}

