/**
 * RegObs API, build: 20251103.4 - commit: 59238037
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionDto } from './position-dto';


export interface WithinExtentCriteriaDto { 
    TopLeft?: PositionDto | null;
    BottomRight?: PositionDto | null;
}

