/**
 * RegObs API, build: Local build - commit: b86cb26d
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionDto } from './position-dto';


export interface WithinExtentCriteriaDto { 
    TopLeft?: PositionDto;
    BottomRight?: PositionDto;
}

