# Sjekker kode og biblioteker for sårbarheter jevnlig

schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
  - job:
    steps:
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: 'javascript'

    - task: NodeTool@0
      displayName: 'Use Node 20.x'
      inputs:
        versionSpec: 20.x
        checkLatest: false

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache npm

    - script: npm ci
      env:
        npm_config_cache: $(npm_config_cache)

    - task: AdvancedSecurity-Dependency-Scanning@1
    - task: AdvancedSecurity-Codeql-Analyze@1
    - task: AdvancedSecurity-Publish@1      
