export enum RegistrationTid {
    Incident = 11,
    DangerObs = 13,
    SnowSurfaceObservation = 22,
    AvalancheActivityObs = 27,
    AvalancheActivityObs2 = 33,
    AvalancheObs = 26,
    WeatherObservation = 21,
    SnowProfile = 36,
    CompressionTest = 25,
    AvalancheEvalProblem2 = 32,
    AvalancheEvaluation3 = 31,
    Picture = 12,
    IceCoverObs = 51,
    IceThickness = 50,
    WaterLevel = 61,
    WaterLevel2 = 62,
    LandSlideObs = 71,
    GeneralObservation = 10,
    DamageObs = 14
}
