export enum RegistrationTypes {
    Incident = 'object',
    DangerObs = 'array',
    AvalancheDangerObs = 'array',
    SnowSurfaceObservation = 'object',
    AvalancheActivityObs = 'array',
    AvalancheActivityObs2 = 'array',
    AvalancheObs = 'object',
    WeatherObservation = 'object',
    SnowProfile = 'object',
    CompressionTest = 'array',
    AvalancheEvalProblem2 = 'array',
    AvalancheEvaluation3 = 'object',
    Picture = 'array',
    IceCoverObs = 'object',
    IceThickness = 'object',
    WaterLevel = 'object',
    WaterLevel2 = 'object',
    LandSlideObs = 'object',
    GeneralObservation = 'object',
    DamageObs = 'array',
    DensityProfile = 'object',
    SnowCoverObs = 'object'
}
