export * from './account.service';
import { AccountService } from './account.service';
export * from './attachment.service';
import { AttachmentService } from './attachment.service';
export * from './geo-code.service';
import { GeoCodeService } from './geo-code.service';
export * from './helptext.service';
import { HelptextService } from './helptext.service';
export * from './kdv-elements.service';
import { KdvElementsService } from './kdv-elements.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './registration.service';
import { RegistrationService } from './registration.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './trip.service';
import { TripService } from './trip.service';
export const APIS = [AccountService, AttachmentService, GeoCodeService, HelptextService, KdvElementsService, LocationService, RegistrationService, SearchService, TripService];
