/**
 * RegObs API, build: Local build - commit: 446d2219
 *
 * Contact: regobs@nve.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { AtAGlanceViewModel } from '../model/at-a-glance-view-model';
// @ts-ignore
import { ProblemDetails } from '../model/problem-details';
// @ts-ignore
import { RegistrationViewModel } from '../model/registration-view-model';
// @ts-ignore
import { RegistrationsWithAttachments } from '../model/registrations-with-attachments';
// @ts-ignore
import { SearchCountResponseDto } from '../model/search-count-response-dto';
// @ts-ignore
import { SearchCriteriaExclUserRequestDto } from '../model/search-criteria-excl-user-request-dto';
// @ts-ignore
import { SearchCriteriaRequestDto } from '../model/search-criteria-request-dto';
// @ts-ignore
import { SearchSideBarDto } from '../model/search-side-bar-dto';
// @ts-ignore
import { SearchSideBarRequestDto } from '../model/search-side-bar-request-dto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface SearchAtAGlanceRequestParams {
    /** Search criteria */
    searchCriteriaRequestDto?: SearchCriteriaRequestDto;
}

export interface SearchAttachmentsCountRequestParams {
    /** Search criteria */
    searchCriteriaRequestDto?: SearchCriteriaRequestDto;
}

export interface SearchCountRequestParams {
    /** Search criteria */
    searchCriteriaRequestDto?: SearchCriteriaRequestDto;
}

export interface SearchCountMyRegistrationsRequestParams {
    /** You may add additional filters */
    searchCriteriaExclUserRequestDto?: SearchCriteriaExclUserRequestDto;
}

export interface SearchGetRegIdsFromDeletedRegistrationsRequestParams {
    /** Search criteria */
    searchCriteriaRequestDto?: SearchCriteriaRequestDto;
}

export interface SearchGetSearchCriteriaRequestParams {
    /** A comma separated list of geo hazard ID\&#39;s. Snow &#x3D; 10, dirt &#x3D; 20, water &#x3D; 60, ice &#x3D; 70. At least one geo hazard is required. */
    geoHazards: string;
    /** NO &#x3D; 1, EN &#x3D; 2, DE &#x3D; 3, SL &#x3D; 4, SV &#x3D; 5, IT &#x3D; 6, NN &#x3D; 7 */
    langKey: number;
}

export interface SearchSearchRequestParams {
    /** Use this to filter out registrations and change ordering of them. The attribute \&quot;ObserverGuid\&quot; is deprecated and will be removed in the future. */
    searchCriteriaRequestDto?: SearchCriteriaRequestDto;
}

export interface SearchSearchCriteriaRequestParams {
    /** A request for relevant search criteria */
    searchSideBarRequestDto?: SearchSideBarRequestDto;
}

export interface SearchSearchImagesRequestParams {
    /** Search criteria */
    searchCriteriaRequestDto?: SearchCriteriaRequestDto;
}

export interface SearchSearchMyRegistrationsRequestParams {
    /** Use this to filter out registrations and change ordering of them */
    searchCriteriaExclUserRequestDto?: SearchCriteriaExclUserRequestDto;
}


@Injectable({
  providedIn: 'root'
})
export class SearchService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Simplified search for registrations. Returns less data per registration, so faster than /Search Returns empty list if no registrations found. Returns only first attachment and count on how many other attachments user can expect when opening a detailed info
     * @endpoint post /Search/AtAGlance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchAtAGlance(requestParameters?: SearchAtAGlanceRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<AtAGlanceViewModel>>;
    public searchAtAGlance(requestParameters?: SearchAtAGlanceRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<AtAGlanceViewModel>>>;
    public searchAtAGlance(requestParameters?: SearchAtAGlanceRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<AtAGlanceViewModel>>>;
    public searchAtAGlance(requestParameters?: SearchAtAGlanceRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaRequestDto = requestParameters?.searchCriteriaRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/AtAGlance`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<AtAGlanceViewModel>>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns search result count for registrations with attachments
     * @endpoint post /Search/Attachments/Count
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchAttachmentsCount(requestParameters?: SearchAttachmentsCountRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<SearchCountResponseDto>;
    public searchAttachmentsCount(requestParameters?: SearchAttachmentsCountRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SearchCountResponseDto>>;
    public searchAttachmentsCount(requestParameters?: SearchAttachmentsCountRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SearchCountResponseDto>>;
    public searchAttachmentsCount(requestParameters?: SearchAttachmentsCountRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaRequestDto = requestParameters?.searchCriteriaRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/Attachments/Count`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SearchCountResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns search result count
     * @endpoint post /Search/Count
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchCount(requestParameters?: SearchCountRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<SearchCountResponseDto>;
    public searchCount(requestParameters?: SearchCountRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SearchCountResponseDto>>;
    public searchCount(requestParameters?: SearchCountRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SearchCountResponseDto>>;
    public searchCount(requestParameters?: SearchCountRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaRequestDto = requestParameters?.searchCriteriaRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/Count`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SearchCountResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns number of registrations that were registered by the logged in user
     * @endpoint post /Search/MyRegistrationsCount
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchCountMyRegistrations(requestParameters?: SearchCountMyRegistrationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<SearchCountResponseDto>;
    public searchCountMyRegistrations(requestParameters?: SearchCountMyRegistrationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SearchCountResponseDto>>;
    public searchCountMyRegistrations(requestParameters?: SearchCountMyRegistrationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SearchCountResponseDto>>;
    public searchCountMyRegistrations(requestParameters?: SearchCountMyRegistrationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaExclUserRequestDto = requestParameters?.searchCriteriaExclUserRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/MyRegistrationsCount`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SearchCountResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaExclUserRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns list of regIds from deleted registrations that can be filtered with criteria model. Used with offline syncing on mobile devices.
     * @endpoint post /Search/DeletedRegistrations
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchGetRegIdsFromDeletedRegistrations(requestParameters?: SearchGetRegIdsFromDeletedRegistrationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<number>>;
    public searchGetRegIdsFromDeletedRegistrations(requestParameters?: SearchGetRegIdsFromDeletedRegistrationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<number>>>;
    public searchGetRegIdsFromDeletedRegistrations(requestParameters?: SearchGetRegIdsFromDeletedRegistrationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<number>>>;
    public searchGetRegIdsFromDeletedRegistrations(requestParameters?: SearchGetRegIdsFromDeletedRegistrationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaRequestDto = requestParameters?.searchCriteriaRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/DeletedRegistrations`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<number>>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns relevant search criteria for the specified geo hazard types and language. This can help you to find the right criteria to use in the other search methods.
     * @endpoint get /Search/SearchCriteria/{geoHazards}/{langKey}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchGetSearchCriteria(requestParameters: SearchGetSearchCriteriaRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<SearchSideBarDto>;
    public searchGetSearchCriteria(requestParameters: SearchGetSearchCriteriaRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SearchSideBarDto>>;
    public searchGetSearchCriteria(requestParameters: SearchGetSearchCriteriaRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SearchSideBarDto>>;
    public searchGetSearchCriteria(requestParameters: SearchGetSearchCriteriaRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const geoHazards = requestParameters?.geoHazards;
        if (geoHazards === null || geoHazards === undefined) {
            throw new Error('Required parameter geoHazards was null or undefined when calling searchGetSearchCriteria.');
        }
        const langKey = requestParameters?.langKey;
        if (langKey === null || langKey === undefined) {
            throw new Error('Required parameter langKey was null or undefined when calling searchGetSearchCriteria.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/SearchCriteria/${this.configuration.encodeParam({name: "geoHazards", value: geoHazards, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/${this.configuration.encodeParam({name: "langKey", value: langKey, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SearchSideBarDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of complete registrations that matches your filter. Empty list if no registrations found. Use POST /Search/AtAGlance for faster search.
     * Example critera for returning the 10 newest registrations: &#x60;&#x60;&#x60; { \&quot;NumberOfRecords\&quot;: 10 } &#x60;&#x60;&#x60;
     * @endpoint post /Search
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchSearch(requestParameters?: SearchSearchRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<RegistrationViewModel>>;
    public searchSearch(requestParameters?: SearchSearchRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<RegistrationViewModel>>>;
    public searchSearch(requestParameters?: SearchSearchRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<RegistrationViewModel>>>;
    public searchSearch(requestParameters?: SearchSearchRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaRequestDto = requestParameters?.searchCriteriaRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<RegistrationViewModel>>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Please use GET /Search/SearchCriteria instead. Returns relevant search criteria for the specified geo hazard types and language. This can help you to find the right criteria to use in the other search methods.
     * @endpoint post /Search/SearchCriteria
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public searchSearchCriteria(requestParameters?: SearchSearchCriteriaRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<SearchSideBarDto>;
    public searchSearchCriteria(requestParameters?: SearchSearchCriteriaRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SearchSideBarDto>>;
    public searchSearchCriteria(requestParameters?: SearchSearchCriteriaRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SearchSideBarDto>>;
    public searchSearchCriteria(requestParameters?: SearchSearchCriteriaRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchSideBarRequestDto = requestParameters?.searchSideBarRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/SearchCriteria`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SearchSideBarDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchSideBarRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search for images only
     * @endpoint post /Search/Attachments
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchSearchImages(requestParameters?: SearchSearchImagesRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<RegistrationsWithAttachments>>;
    public searchSearchImages(requestParameters?: SearchSearchImagesRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<RegistrationsWithAttachments>>>;
    public searchSearchImages(requestParameters?: SearchSearchImagesRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<RegistrationsWithAttachments>>>;
    public searchSearchImages(requestParameters?: SearchSearchImagesRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaRequestDto = requestParameters?.searchCriteriaRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/Attachments`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<RegistrationsWithAttachments>>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of complete registrations that were registered by the logged in user. Empty list if no registrations found.
     * Example critera for returning the 10 newest registrations: &#x60;&#x60;&#x60; { \&quot;NumberOfRecords\&quot;: 10 } &#x60;&#x60;&#x60;
     * @endpoint post /Search/MyRegistrations
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchSearchMyRegistrations(requestParameters?: SearchSearchMyRegistrationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<RegistrationViewModel>>;
    public searchSearchMyRegistrations(requestParameters?: SearchSearchMyRegistrationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<RegistrationViewModel>>>;
    public searchSearchMyRegistrations(requestParameters?: SearchSearchMyRegistrationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<RegistrationViewModel>>>;
    public searchSearchMyRegistrations(requestParameters?: SearchSearchMyRegistrationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const searchCriteriaExclUserRequestDto = requestParameters?.searchCriteriaExclUserRequestDto;

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey', 'regObs_apptoken', localVarHeaders);

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/Search/MyRegistrations`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<RegistrationViewModel>>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: searchCriteriaExclUserRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
