export type KdvKey =
    'Dirt_DangerSignKDV' |
    'Dirt_ActivityInfluencedKDV' |
    'Dirt_LandSlideKDV' |
    'Dirt_LandSlideTriggerKDV' |
    'Dirt_LandSlideSizeKDV' |
    'Ice_DangerSignKDV' |
    'Ice_ActivityInfluencedKDV' |
    'Ice_IceCoverKDV' |
    'Ice_IceCoverBeforeKDV' |
    'Ice_IceLayerKDV' |
    'Ice_IceSkateabilityKDV' |
    'Ice_IceCapacityKDV' |
    'Ice_IceProblemKDV' |
    'Snow_DangerSignKDV' |
    'Snow_ActivityInfluencedKDV' |
    'Snow_AvalancheKDV' |
    'Snow_AvalancheDangerKDV' |
    'Snow_AvalancheExtKDV' |
    'Snow_AvalCauseKDV' |
    'Snow_AvalCauseDepthKDV' |
    'Snow_AvalCauseAttributeFlags' |
    'Snow_AvalProbabilityKDV' |
    'Snow_AvalPropagationKDV' |
    'Snow_AvalReleaseHeightKDV' |
    'Snow_AvalTriggerSimpleKDV' |
    'Snow_DestructiveSizeKDV' |
    'Snow_SnowDriftKDV' |
    'Snow_EstimatedNumKDV' |
    'Snow_ExposedHeightComboKDV' |
    'Snow_ForecastCorrectKDV' |
    'Snow_PrecipitationKDV' |
    'Snow_AvalancheTriggerKDV' |
    'Snow_TerrainStartZoneKDV' |
    'Snow_SnowSurfaceKDV' |
    'Snow_SurfaceWaterContentKDV' |
    'Snow_StabilityEvalKDV' |
    'Snow_ComprTestFractureKDV' |
    'Snow_PropagationKDV' |
    'Snow_WetnessKDV' |
    'Snow_HardnessKDV' |
    'Snow_GrainFormKDV' |
    'Snow_CriticalLayerKDV' |
    'Water_DangerSignKDV' |
    'Water_ActivityInfluencedKDV' |
    'Water_WaterLevelRefKDV' |
    'Water_WaterLevelStateKDV' |
    'Water_WaterAstrayKDV' |
    'Water_ObservationTimingKDV' |
    'Water_WaterLevelMethodKDV' |
    'Water_MeasurementTypeKDV' |
    'Water_MeasurementReferenceKDV' |
    'Water_MarkingReferenceKDV' |
    'Water_MarkingTypeKDV' |
    'Water_DamageTypeKDV' |
    'AnticipatedObservationTimeKDV' |
    'ForecastAccurateKDV' |
    'DamageExtentKDV' |
    'CompetenceLevelKDV' |
    'UTMSourceKDV' |
    'TripTypeKDV' |
    'GeoHazardKDV' |
    'UsageFlagKDV' |
    'RegistrationKDV' |
    'SourceKDV'
    ;
