/**
 * Grain form code (IACS) to Regobs TID
 */
export enum GrainForm {
  ' - ' = 0,
  'PP' = 1,
  'PPco' = 2,
  'PPnd' = 3,
  'PPpl' = 4,
  'PPsd' = 5,
  'PPir' = 6,
  'PPgp' = 7,
  'PPhl' = 8,
  'PPip' = 9,
  'PPrm' = 10,
  'MM' = 11,
  'MMrp' = 12,
  'MMci' = 13,
  'DF' = 14,
  'DFdc' = 15,
  'DFbk' = 16,
  'RG' = 17,
  'RGsr' = 18,
  'RGlr' = 19,
  'RGwp' = 20,
  'RGxf' = 21,
  'FC' = 22,
  'FCso' = 23,
  'FCsf' = 24,
  'FCxr' = 25,
  'DH' = 26,
  'DHcp' = 27,
  'DHpr' = 28,
  'DHch' = 29,
  'DHla' = 30,
  'DHxr' = 31,
  'SH' = 32,
  'SHsu' = 33,
  'SHcv' = 34,
  'SHxr' = 35,
  'MF' = 36,
  'MFcl' = 37,
  'MFpc' = 38,
  'MFsl' = 39,
  'MFcr' = 40,
  'IF' = 41,
  'IFil' = 42,
  'IFic' = 43,
  'IFbi' = 44,
  'IFrc' = 45,
  'IFsc' = 46,
}

/**
 * Snow symbol code (IACS) to alphabet key
 */
const GRAIN_FORM_KEY = {
  [GrainForm[' - ']]: '', // undefined
  [GrainForm.PP]: 'a',
  [GrainForm.MM]: 'b',
  [GrainForm.DF]: 'c',
  [GrainForm.RG]: 'd',
  [GrainForm.FC]: 'e',
  [GrainForm.DH]: 'f',
  [GrainForm.SH]: 'g',
  [GrainForm.MF]: 'h',
  [GrainForm.IF]: 'i',
  [GrainForm.PPco]: 'j',
  [GrainForm.PPnd]: 'k',
  [GrainForm.PPpl]: 'l',
  [GrainForm.PPsd]: 'm',
  [GrainForm.PPir]: 'n',
  [GrainForm.PPgp]: 'o',
  [GrainForm.PPhl]: 'p',
  [GrainForm.PPip]: 'q',
  [GrainForm.PPrm]: 'r',
  [GrainForm.MMrp]: 's',
  [GrainForm.MMci]: 't',
  [GrainForm.DFdc]: 'u',
  [GrainForm.DFbk]: 'v',
  [GrainForm.RGsr]: 'w',
  [GrainForm.RGlr]: 'x',
  [GrainForm.RGwp]: 'y',
  [GrainForm.RGxf]: 'z',
  [GrainForm.FCso]: 'A',
  [GrainForm.FCsf]: 'B',
  [GrainForm.FCxr]: 'C',
  [GrainForm.DHcp]: 'D',
  [GrainForm.DHpr]: 'E',
  [GrainForm.DHch]: 'F',
  [GrainForm.DHla]: 'G',
  [GrainForm.DHxr]: 'H',
  [GrainForm.SHsu]: 'I',
  [GrainForm.SHcv]: 'J',
  [GrainForm.SHxr]: 'K',
  [GrainForm.MFcl]: 'L',
  [GrainForm.MFpc]: 'M',
  [GrainForm.MFsl]: 'N',
  [GrainForm.MFcr]: 'O',
  [GrainForm.IFil]: 'P',
  [GrainForm.IFic]: 'Q',
  [GrainForm.IFbi]: 'R',
  [GrainForm.IFrc]: 'S',
  [GrainForm.IFsc]: 'T',
  // '(': '(',
  // ')': ')',
  // '4F': '2',
  // '1F': '3',
  // P: '4',
  // K: '5',
  // M: '7',
  // W: '8',
  // V: '9',
  // S: '0',
  // SFrsm: 'U',
  // SFrwa: 'V',
  // SFrcv: 'W',
  // SFrcx: 'X',
  // SFrrd: 'Y',
  // drift: '%',
  // barchan: '&',
  // 'sun cup': '?',
  // penitent: '!',
};

export const grainFormTidToSnowSymbolKey = (tid: GrainForm): string => {
  return GRAIN_FORM_KEY[tid];
};
